/*
 * Impostor MX - Juego de fiesta libre y gratuito
 * Copyright (C) 2026 Retired64 
 *
 * Este programa es software libre: puedes redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General GNU publicada por
 * la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a tu elección) cualquier versión posterior.
 *
 * Este programa se distribuye con la esperanza de que sea útil,
 * pero SIN NINGUNA GARANTÍA; sin siquiera la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Consulta la
 * Licencia Pública General GNU para más detalles.
 *
 * Deberías haber recibido una copia de la Licencia Pública General GNU
 * junto con este programa. Si no es así, consulta <https://www.gnu.org/licenses/>.
 */

import 'package:flutter/material.dart';

// ==========================================
// MODELO DE DATOS (CATEGORÍA)
// ==========================================

class Category {
  final String id;
  final String name;
  final String icon;
  final List<String> words;
  final Color color;

  const Category({
    required this.id,
    required this.name,
    required this.icon,
    required this.words,
    required this.color,
  });

  // --- NUEVO: Lógica para Guardar/Cargar (Serialización) ---

  // Convertir a Mapa (para guardar en JSON)
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'icon': icon,
      'words': words,
      'colorValue': color.value, // Guardamos el color como número entero
    };
  }

  // Crear desde Mapa (para cargar de JSON)
  factory Category.fromMap(Map<String, dynamic> map) {
    return Category(
      id: map['id'],
      name: map['name'],
      icon: map['icon'],
      words: List<String>.from(map['words']),
      color: Color(map['colorValue']),
    );
  }
}

// ==========================================
// BASE DE DATOS INICIAL (SEED DATA)
// ==========================================

final List<Category> GAME_CATEGORIES = [
  Category(
    id: 'mix',
    name: 'Random',
    icon: '🎲',
    color: Colors.purple,
    words: [
      'Agujero Negro',
      'Alquimista',
      'Amnesia',
      'Apocalipsis',
      'Arqueólogo',
      'Astronauta',
      'Atomo',
      'Avatar',
      'Batería',
      'Bitcoin',
      'Búnker',
      'Caballero Medieval',
      'Caja Fuerte',
      'Camaleón',
      'Carnaval',
      'Catapulta',
      'Cavernícola',
      'Cenicienta',
      'Centauro',
      'Chaman',
      'Ciborg',
      'Ciclón',
      'Cirujano',
      'Clon',
      'Código de Barras',
      'Cometa',
      'Conspiración',
      'Contrabandista',
      'Criptonita',
      'Crucigrama',
      'Cuarentena',
      'Detective',
      'Dinamita',
      'Dinosaurio',
      'Dios Griego',
      'Drácula',
      'Dragón',
      'Dron',
      'Eclípse',
      'Ecuación',
      'Electricidad',
      'Elfo',
      'Emperador',
      'Espía',
      'Esqueleto',
      'Estatal',
      'Estatua',
      'Extraterrestre',
      'Fantasma',
      'Faraón',
      'Fósil',
      'Francotirador',
      'Frankenstein',
      'Fuego',
      'Futuro',
      'Gánster',
      'Genio',
      'Gladiador',
      'Gravedad',
      'Guerra',
      'Guillotina',
      'Hacker',
      'Hada',
      'Hechizo',
      'Helicóptero',
      'Héroe',
      'Hidra',
      'Hipnosis',
      'Holograma',
      'Horóscopo',
      'Huracán',
      'Iceberg',
      'Ilusionista',
      'Imán',
      'Inmortalidad',
      'Internet',
      'Invisible',
      'Jedi',
      'Karma',
      'Katana',
      'Kung Fu',
      'Laberinto',
      'Lámpara Mágica',
      'Láser',
      'Lava',
      'Leyenda',
      'Lluvia Ácida',
      'Lobo Feroz',
      'Lotería',
      'Magia',
      'Magnetismo',
      'Mamut',
      'Manicomio',
      'Máquina del Tiempo',
      'Máscara',
      'Matemáticas',
      'Meteorito',
      'Microchip',
      'Microscopio',
      'Mimo',
      'Mina',
      'Minotauro',
      'Misil',
      'Mochila',
      'Momia',
      'Monje',
      'Monstruo',
      'Mosaico',
      'Mutante',
      'Nanotecnología',
      'Náufrago',
      'Ninja',
      'Nómada',
      'Nuclear',
      'Oasis',
      'Oráculo',
      'Ovni',
      'Pandemia',
      'Paracaídas',
      'Paradoja',
      'Paraíso',
      'Pasmado',
      'Patente',
      'Paz',
      'Pesadilla',
      'Peste',
      'Piedra Filosofal',
      'Pirámide',
      'Pirata',
      'Plutonio',
      'Poción',
      'Portal',
      'Predicción',
      'Profecía',
      'Psíquico',
      'Quimera',
      'Radiactividad',
      'Rayo',
      'Reciclaje',
      'Reliquia',
      'Renacimiento',
      'Resurrección',
      'Revolución',
      'Robot',
      'Samurái',
      'Satélite',
      'Secreto',
      'Secta',
      'Sirena',
      'Sobrenatural',
      'Submarino',
      'Superhéroe',
      'Superviviente',
      'Talismán',
      'Tanque',
      'Tarot',
      'Tatuaje',
      'Telepatía',
      'Teletransportación',
      'Telescopio',
      'Tesoro',
      'Tiranosaurio',
      'Tornado',
      'Tóxico',
      'Trance',
      'Troll',
      'Tsunami',
      'Unicornio',
      'Vampiro',
      'Vikingo',
      'Virus',
      'Volcán',
      'Vudú',
      'Wi-Fi',
      'Yeti',
      'Yoga',
      'Zepelín',
      'Zombie',
      'Zodiaco',
    ],
  ),
  Category(
    id: 'fiesta',
    name: 'Fiesta',
    icon: '🍻',
    color: Colors.pink,
    words: [
      'After',
      'Alcoholímetro',
      'Altavoz',
      'Ambiente',
      'Aniversario',
      'Año Nuevo',
      'Antro',
      'Bacha',
      'Bailarín',
      'Banda de Rock',
      'Banda Sinaloense',
      'Bar',
      'Barman',
      'Boda',
      'Borracho',
      'Botana',
      'Botella',
      'Brindis',
      'Caguama',
      'Cantina',
      'Caña',
      'Cadenero',
      'Carnaval',
      'Carne Asada',
      'Casino',
      'Cerveza',
      'Champán',
      'Chismes',
      'Chupitos',
      'Cigarro',
      'Cóctel',
      'Colado',
      'Coma Etílico',
      'Confeti',
      'Concierto',
      'Conductor Designado',
      'Copas',
      'Coreografía',
      'Corchos',
      'Cruda (Resaca)',
      'Cubeta',
      'Cumpleaños',
      'Despedida de Soltero',
      'DJ',
      'Discoteca',
      'Disfraz',
      'Domingo de Bajón',
      'Dr. Simi',
      'Ebrio',
      'Escenario',
      'Espuma',
      'Fiesta de Disfraces',
      'Fiesta Sorpresa',
      'Fondo',
      'Fuegos Artificiales',
      'Gorra',
      'Graduación',
      'Gritos',
      'Guacarear',
      'Guanajuato',
      'Guitarra',
      'Happy Hour',
      'Hielera',
      'Hielos',
      'Invitación',
      'Jägermeister',
      'Jelly Shots',
      'Juez',
      'Juegos de beber',
      'Karaoke',
      'Las Mañanitas',
      'Licuachela',
      'Limusina',
      'Litros',
      'Luces Neón',
      'Mala Copa',
      'Mariachi',
      'Matasuegras',
      'Mesero',
      'Mezcal',
      'Michelada',
      'Micrófono',
      'Mirrey',
      'Música a todo volumen',
      'Navidad',
      'Noche de Chicas',
      'Nochebuena',
      'Olor a cigarro',
      'Open Bar',
      'Palenque',
      'Palomazo',
      'Pank',
      'Parranda',
      'Pasito Duranguense',
      'Pastel',
      'Payaso',
      'Perreo',
      'Piñata',
      'Pista de Baile',
      'Plática profunda',
      'Playboy',
      'Polvo',
      'Posada',
      'Precopeo',
      'Premios',
      'Propina',
      'Pulque',
      'Quinceañera',
      'Recuerdos',
      'Refresco',
      'Regalo',
      'Reggaetón',
      'Reunión Familiar',
      'Rifa',
      'Rockola',
      'Rompope',
      'Ronda',
      'Rumba',
      'Salsa',
      'San Valentín',
      'Seguridad',
      'Serenata',
      'Shot',
      'Show',
      'Silla Musical',
      'Sonidero',
      'Sudor',
      'Tacos de madrugada',
      'Tarima',
      'Taxi',
      'Tequila',
      'Terraza',
      'Tío Borracho',
      'Torito',
      'Tornaboda',
      'Torta de Tamal',
      'Tragos Coquetos',
      'Traje',
      'Uber',
      'Vals',
      'Vaso Rojo',
      'Vecinos molestos',
      'Vestido de Noche',
      'Vino Tinto',
      'Vip',
      'Vómito',
      'Whisky',
      'XV Años',
      'Zona VIP',
    ],
  ),
  Category(
    id: 'cine',
    name: 'Cine',
    icon: '🎬',
    color: Colors.blue,
    words: [
      'Acción',
      'Actor',
      'Actriz',
      'Alfombra Roja',
      'Alien',
      'Anime',
      'Antagonista',
      'Apocalipsis Zombie',
      'Audición',
      'Autógrafo',
      'Avatar',
      'Beso de película',
      'Blockbuster',
      'Bloopers',
      'Bollywood',
      'Butaca',
      'Cámara',
      'Camerino',
      'Casting',
      'Cartelera',
      'Casa de Papel',
      'CGI (Efectos)',
      'Cine Mudo',
      'Cineasta',
      'Claqueta',
      'Clímax',
      'Comedia',
      'Comercial',
      'Continuidad',
      'Cortometraje',
      'Créditos',
      'Crimen',
      'Crítico de Cine',
      'Crossover',
      'Director',
      'Disney',
      'Doble de acción',
      'Documental',
      'Drama',
      'Dron',
      'Edición',
      'Efectos Especiales',
      'El Señor de los Anillos',
      'Emmy',
      'En Vivo',
      'Escena Post-créditos',
      'Escenografía',
      'Estatuilla',
      'Estreno',
      'Estudio',
      'Extra',
      'Famoso',
      'Fantasía',
      'Festival de Cannes',
      'Flashback',
      'Foco',
      'Fotografía',
      'Game of Thrones',
      'Género',
      'Globo de Oro',
      'Godzilla',
      'Guion',
      'Guionista',
      'Harry Potter',
      'Héroe',
      'Hollywood',
      'Iluminación',
      'Influencer',
      'Intro',
      'Jumpscare',
      'Jurassic Park',
      'Lente',
      'Maquillaje',
      'Maratón',
      'Marvel',
      'Mickey Mouse',
      'Micrófono',
      'Miniserie',
      'Monólogo',
      'Montaje',
      'Música de fondo',
      'Musical',
      'Netflix',
      'Noticiero',
      'Novela',
      'Oscar',
      'Palomitas',
      'Pantalla Grande',
      'Pantalla Verde',
      'Paparazzi',
      'Película de Terror',
      'Película Muda',
      'Personaje',
      'Piratas del Caribe',
      'Pixar',
      'Plano Secuencia',
      'Plataforma de Streaming',
      'Plot Twist',
      'Póster',
      'Premio',
      'Presentador',
      'Primicia',
      'Productor',
      'Proyector',
      'Publicidad',
      'Reality Show',
      'Reboot',
      'Remake',
      'Reportero',
      'Rodaje',
      'Romance',
      'Saga',
      'Secuela',
      'Serie',
      'Set de grabación',
      'Show de Talentos',
      'Sitcom',
      'Sonidista',
      'Soundtrack',
      'Spider-Man',
      'Spoiler',
      'Star Wars',
      'Streaming',
      'Superhéroe',
      'Suspenso',
      'Talk Show',
      'Taquilla',
      'Teatro',
      'Telenovela',
      'Televisión',
      'Temporada',
      'Thriller',
      'Titanic',
      'Tomates',
      'Tragedia',
      'Tráiler',
      'Trama',
      'Transmisión',
      'Vestuario',
      'VHS',
      'Villano',
      'Western',
      'YouTube',
      'Zombie',
    ],
  ),
  Category(
    id: 'comida',
    name: 'Comida',
    icon: '🌮',
    color: Colors.orange,
    words: [
      'Aceite de Oliva',
      'Aguacate',
      'Ajo',
      'Albóndigas',
      'Alitas',
      'Arroz',
      'Atún',
      'Avena',
      'Azúcar',
      'Bacalao',
      'Bacon (Tocino)',
      'Bagel',
      'Baguette',
      'Barbacoa',
      'Batido',
      'Birria',
      'Bistec',
      'Bolillo',
      'Boneless',
      'Brocheta',
      'Brownie',
      'Buffet',
      'Burrito',
      'Café',
      'Calabaza',
      'Caldo de Pollo',
      'Camarones',
      'Canela',
      'Caramelo',
      'Carne Asada',
      'Caviar',
      'Cebolla',
      'Cena',
      'Cereal',
      'Champiñón',
      'Chef',
      'Cheesecake',
      'Chicharrón',
      'Chilaquiles',
      'Chile',
      'Chile en Nogada',
      'Chimichanga',
      'Chocolate',
      'Chorizo',
      'Churros',
      'Cilantro',
      'Clara de Huevo',
      'Coco',
      'Comida China',
      'Comida Rápida',
      'Concha (Pan)',
      'Cremas',
      'Crepas',
      'Croissant',
      'Curry',
      'Desayuno',
      'Dona',
      'Doritos',
      'Dulce de Leche',
      'Elote',
      'Empanada',
      'Enchiladas',
      'Ensalada',
      'Espagueti',
      'Esquites',
      'Filete',
      'Flan',
      'Fresa',
      'Frijoles',
      'Fruta',
      'Galleta',
      'Gelatina',
      'Gordita',
      'Guacamole',
      'Hamburguesa',
      'Harina',
      'Helado',
      'Hot Dog',
      'Hot Cakes',
      'Huevo',
      'Huevo Kinder',
      'Jamon',
      'Jugo',
      'Kétchup',
      'Kiwi',
      'Langosta',
      'Lasaña',
      'Leche',
      'Lechuga',
      'Limón',
      'Longaniza',
      'Macarrones',
      'Maíz',
      'Mantequilla',
      'Manzana',
      'Mariscos',
      'Mayonesa',
      'Mazapán',
      'Menudo',
      'Mermelada',
      'Miel',
      'Milanesa',
      'Mole',
      'Molletes',
      'Mostaza',
      'Muffin',
      'Nachos',
      'Naranja',
      'Nuggets',
      'Nuez',
      'Omelette',
      'Ostiones',
      'Paella',
      'Pan de Muerto',
      'Pan Tostado',
      'Pancita',
      'Papa al horno',
      'Papas Fritas',
      'Pasta',
      'Pastel',
      'Pato',
      'Pepino',
      'Pescado',
      'Pimienta',
      'Piña',
      'Pizza',
      'Plátano',
      'Pollo Frito',
      'Pozole',
      'Quesadilla',
      'Queso',
      'Ramen',
      'Ravioles',
      'Refresco',
      'Rosca de Reyes',
      'Sal',
      'Salchicha',
      'Salmón',
      'Salsa Verde',
      'Sandía',
      'Sándwich',
      'Sopa',
      'Sope',
      'Sushi',
      'Tacos',
      'Tacos al Pastor',
      'Tacos de Canasta',
      'Tamales',
      'Tarta',
      'Tocino',
      'Tomate',
      'Torta',
      'Tostada',
      'Totopos',
      'Trufa',
      'Uvas',
      'Vainilla',
      'Verduras',
      'Vinagre',
      'Waffles',
      'Yogur',
      'Zanahoria',
    ],
  ),
  Category(
    id: 'lugares',
    name: 'Lugares',
    icon: '✈️',
    color: Colors.teal,
    words: [
      'Acampada',
      'Aeropuerto',
      'Agencia de Viajes',
      'Alberca',
      'Antártida',
      'Antro',
      'Apartamento',
      'Área 51',
      'Ascensor',
      'Autobús',
      'Autolavado',
      'Autopista',
      'Banco',
      'Baño Público',
      'Barbería',
      'Base Militar',
      'Biblioteca',
      'Bosque',
      'Cabaña',
      'Cafetería',
      'Callejón',
      'Campo de Golf',
      'Cancha de Fútbol',
      'Cantina',
      'Capilla',
      'Cárcel',
      'Carnicería',
      'Casa Blanca',
      'Casa Embrujada',
      'Casino',
      'Castillo',
      'Catedral',
      'Cementerio',
      'Central de Abastos',
      'Centro Comercial',
      'Cine',
      'Circo',
      'Ciudad Perdida',
      'Cocina',
      'Coliseo Romano',
      'Comisaría',
      'Concierto',
      'Confesionario',
      'Consultorio',
      'Correo',
      'Crucero',
      'Cueva',
      'Desierto',
      'Disneyland',
      'Edificio',
      'Egipto',
      'Embajada',
      'Escuela',
      'Estación de Bomberos',
      'Estación de Policía',
      'Estación de Tren',
      'Estación Espacial',
      'Estadio',
      'Estética',
      'Fábrica',
      'Farmacia',
      'Feria',
      'Frontera',
      'Funeraria',
      'Galería de Arte',
      'Gasolinera',
      'Gimnasio',
      'Granja',
      'Guardería',
      'Habitación',
      'Heladería',
      'Hospital',
      'Hotel',
      'Iglesia',
      'Iglesia',
      'Iglú',
      'Infierno',
      'Isla Desierta',
      'Jardín',
      'Joyería',
      'Jungla',
      'Laboratorio',
      'Lago',
      'Lavandería',
      'Librería',
      'Limusina',
      'Luna',
      'Manicomio',
      'Mansión',
      'Marte',
      'Mercado',
      'Metro',
      'Mina',
      'Mirador',
      'Motel',
      'Muelle',
      'Muralla China',
      'Museo',
      'Nave Espacial',
      'Oasis',
      'Oficina',
      'Ópera',
      'Orfanato',
      'Panadería',
      'Panteón',
      'Parada de Autobús',
      'París',
      'Parque',
      'Parque de Atracciones',
      'Patio',
      'Peluquería',
      'Penthouse',
      'Piscina',
      'Pizzería',
      'Planeta',
      'Playa',
      'Plaza',
      'Polo Norte',
      'Puente',
      'Puerto',
      'Quiosco',
      'Rascacielos',
      'Restaurante',
      'Río',
      'Ruinas',
      'Sala de Juicios',
      'Salón de Clases',
      'Sauna',
      'Selva',
      'Semáforo',
      'Spa',
      'Submarino',
      'Supermercado',
      'Taller Mecánico',
      'Taquería',
      'Teatro',
      'Tejado',
      'Templo',
      'Tienda de Mascotas',
      'Tienda de Ropa',
      'Torre Eiffel',
      'Torre de Control',
      'Túnel',
      'Universidad',
      'Veterinaria',
      'Volcán',
      'Zoológico',
    ],
  ),
  Category(
    id: 'animales',
    name: 'Animal',
    icon: '🦁',
    color: Colors.green,
    words: [
      'Abeja',
      'Águila',
      'Ajolote',
      'Alce',
      'Araña',
      'Ardilla',
      'Armadillo',
      'Avestruz',
      'Ballena',
      'Búho',
      'Burro',
      'Caballo',
      'Cabra',
      'Camello',
      'Cangrejo',
      'Canguro',
      'Capibara',
      'Castor',
      'Cebra',
      'Cerdo',
      'Chango',
      'Chita',
      'Cisne',
      'Cocodrilo',
      'Colibrí',
      'Conejo',
      'Coyote',
      'Delfín',
      'Elefante',
      'Escorpión',
      'Flamenco',
      'Foca',
      'Gallina',
      'Gato',
      'Gorila',
      'Grillo',
      'Gusano',
      'Hámster',
      'Hipopótamo',
      'Hormiga',
      'Hurón',
      'Iguana',
      'Jaguar',
      'Jirafa',
      'Koala',
      'León',
      'Leopardo',
      'Llama',
      'Lobo',
      'Loro',
      'Mapache',
      'Mariposa',
      'Medusa',
      'Mono',
      'Mosca',
      'Murciélago',
      'Nutria',
      'Oso Panda',
      'Oso Polar',
      'Oveja',
      'Pato',
      'Pavo Real',
      'Perro',
      'Pez Payaso',
      'Pingüino',
      'Pollo',
      'Pulpo',
      'Rana',
      'Ratón',
      'Rinoceronte',
      'Serpiente',
      'Tiburón',
      'Tigre',
      'Tortuga',
      'Vaca',
      'Venado',
      'Zorro',
    ],
  ),
];
