/*
 * Impostor MX - Juego de fiesta libre y gratuito
 * Copyright (C) 2026 Retired64
 */

import 'package:flutter/material.dart';

// ==========================================
// MODELO DE DATOS (CATEGORÍA)
// ==========================================

class Category {
  final String id;
  final String name;
  final String icon;
  final List<String> words;
  final Color color;

  const Category({
    required this.id,
    required this.name,
    required this.icon,
    required this.words,
    required this.color,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'icon': icon,
      'words': words,
      'colorValue': color.value,
    };
  }

  factory Category.fromMap(Map<String, dynamic> map) {
    return Category(
      id: map['id'],
      name: map['name'],
      icon: map['icon'],
      words: List<String>.from(map['words']),
      color: Color(map['colorValue']),
    );
  }
}

// ==========================================
// CONTROLADOR DE IDIOMAS PARA LAS CARTAS
// ==========================================

List<Category> getGameCategories(String langCode) {
  switch (langCode) {
    case 'en':
      return _categoriesEn;
    case 'pt':
      return _categoriesPt;
    case 'es':
    default:
      return _categoriesEs;
  }
}

// ==========================================
// BASE DE DATOS: ESPAÑOL (~2100 palabras)
// ==========================================
final List<Category> _categoriesEs = [
  const Category(
    id: 'mix',
    name: 'Random',
    icon: '🎲',
    color: Colors.purple,
    words: [
      'Agujero Negro',
      'Alquimista',
      'Amnesia',
      'Apocalipsis',
      'Astronauta',
      'Átomo',
      'Avatar',
      'Batería',
      'Bitcoin',
      'Búnker',
      'Caballero',
      'Camaleón',
      'Catapulta',
      'Cenicienta',
      'Centauro',
      'Ciborg',
      'Dinosaurio',
      'Dragón',
      'Esfinge',
      'Extraterrestre',
      'Fantasma',
      'Frankenstein',
      'Genio',
      'Gravedad',
      'Hechizo',
      'Hada',
      'Hipnosis',
      'Ilusión',
      'Karma',
      'Laberinto',
      'Magia',
      'Momia',
      'Mutante',
      'Ninja',
      'Ovni',
      'Pirata',
      'Portal',
      'Robot',
      'Sirena',
      'Superhéroe',
      'Telepatía',
      'Vampiro',
      'Vikingo',
      'Zombi',
      'Alquimia',
      'Andrés',
      'Apocalipsis',
      'Arcoíris',
      'Arquero',
      'Ataúd',
      'Atlántico',
      'Aurora Boreal',
      'Bigfoot',
      'Bruja',
      'Brujería',
      'Calavera',
      'Capa Invisible',
      'Cápsula del Tiempo',
      'Cataclismo',
      'Clon',
      'Código Secreto',
      'Cometa',
      'Constelación',
      'Criptonita',
      'Cristal Mágico',
      'Cueva',
      'Cyber',
      'Deja Vu',
      'Destino',
      'Dimensión',
      'Diosa',
      'Eclipse',
      'Elfo',
      'Enano',
      'Encrucijada',
      'Energía',
      'Enigma',
      'Esclavo',
      'Espejismo',
      'Espía',
      'Espíritu',
      'Estrella',
      'Explosión',
      'Faraón',
      'Fecha Límite',
      'Fenix',
      'Fósil',
      'Gárgola',
      'Gladiador',
      'Golem',
      'Grifo',
      'Guerrero',
      'Holograma',
      'Hombre Lobo',
      'Ícaro',
      'Imperador',
      'Ladrón',
      'Leyenda',
      'Linterna',
      'Llave Maestra',
      'Maestro',
      'Mariposa de Fuego',
      'Matrix',
      'Medusa',
      'Mente Colmena',
      'Mentiroso',
      'Meteorito',
      'Minotauro',
      'Misterio',
      'Mito',
      'Morgana',
      'Monje',
      'Nirvana',
      'Oráculo',
      'Orco',
      'Oscuridad',
      'Pegaso',
      'Poltergeist',
      'Poseidón',
      'Profecía',
      'Prometheus',
      'Quimera',
      'Resurrección',
      'Rex',
      'Ritual',
      'Runas',
      'Samurái',
      'Satélite',
      'Sombra',
      'Sortilegio',
      'Subconsciente',
      'Talismán',
      'Templo',
      'Tiempo',
      'Titán',
      'Tótem',
      'Troll',
      'Tsunami',
      'Unicornio',
      'Universo Paralelo',
      'Valkiria',
      'Warlock',
      'Wormhole',
      'Yeti',
      'Zeus',
      'Zombie Apocalypse',
      'Zona Muerta',
      'Abismo',
      'Acertijo',
      'Ángel Caído',
      'Anomalía',
      'Antimateria',
      'Arma Secreta',
      'Astral',
      'Aura',
      'Bestia',
      'Biomecánico',
      'Caos',
      'Centinela',
      'Chakra',
      'Código Binario',
      'Convergencia',
      'Corona Mágica',
      'Cripta',
      'Cristal de Poder',
      'Cruzada',
      'Curandera',
      'Cyberpunk',
      'Daemon',
      'Desaparición',
      'Desintegración',
      'Dios Olvidado',
      'Distopia',
      'Divino',
      'Dominio',
      'Doppelganger',
      'Encantamiento',
      'Espadachín',
      'Espectro',
      'Eterno',
      'Éter',
      'Exorcismo',
      'Fatalidad',
      'Fuerza Oscura',
      'Galaxia',
      'Grieta Dimensional',
      'Guardián',
      'Gyromancer',
      'Hermandad',
      'Heroína',
      'Hombre de Arena',
      'Horizonte',
      'Icono',
      'Inframundo',
      'Interdimensional',
      'Invisibilidad',
      'Legilimancia',
      'Liche',
      'Mente Maestra',
      'Metamorfosis',
      'Mundo Espejo',
      'Néctar',
      'Necrópolis',
      'Nexo',
      'Nigromante',
      'Ninfas',
      'Noche Eterna',
      'Núcleo',
      'Obsidiana',
      'Ogro',
      'Omnisciente',
      'Ónix',
      'Pacto Oscuro',
      'Paradoja',
      'Parlanchín',
      'Planeta Rojo',
      'Polvo Estelar',
      'Primitivo',
      'Prófugo',
      'Reencarnación',
      'Relicario',
      'Sello',
      'Señal',
      'Simulacro',
      'Singularidad',
      'Sorteo',
      'Subterráneo',
      'Supernovas',
      'Telepático',
      'Testamento',
      'Trampa',
      'Trangresión',
      'Viaje Astral',
      'Visión',
      'Vórtice',
      'Zafiro Maldito',
      'Ancla Cósmica',
      'Armadura de Sombra',
      'Bruma Eterna',
      'Catarata de Fuego',
      'Cicatriz del Tiempo',
      'Código de Honor',
      'Cuarzo Negro',
      'Destello',
      'Esencia Pura',
      'Espada Rúnica',
      'Forma Cambiante',
      'Fragmento',
      'Glaciar Mágico',
      'Grimorio',
    ],
  ),
  const Category(
    id: 'fiesta',
    name: 'Fiesta',
    icon: '🍻',
    color: Colors.pink,
    words: [
      'Alcoholímetro',
      'Altavoz',
      'Año Nuevo',
      'Antro',
      'Barman',
      'Boda',
      'Borracho',
      'Botana',
      'Cerveza',
      'Champán',
      'Concierto',
      'Cruda',
      'DJ',
      'Disfraz',
      'Karaoke',
      'Shot',
      'Piñata',
      'Pastel',
      'Globos',
      'Invitación',
      'Baile',
      'Resaca',
      'Tequila',
      'Vodka',
      'Ron',
      'Vino',
      'Hielo',
      'Vaso',
      'Brindis',
      'Despedida de Soltero',
      'Confeti',
      'VIP',
      'Pulsera',
      'Guardia',
      'After Party',
      'Animador',
      'Barra Libre',
      'Barril',
      'Botellazo',
      'Botella',
      'Buffet',
      'Cabina',
      'Cantina',
      'Carnaval',
      'Casinos',
      'Celebración',
      'Cerveza Artesanal',
      'Cóctel',
      'Cohete',
      'Copa',
      'Cotillón',
      'Cubilete',
      'Cumpleaños',
      'Discoteca',
      'Disfrazado',
      'Drink',
      'Euforia',
      'Fiesta Temática',
      'Flores',
      'Fogata',
      'Fuegos Artificiales',
      'Ginebra',
      'Gorra',
      'Grifo de Cerveza',
      'Grupo Musical',
      'Happy Hour',
      'Horchata',
      'Jarra',
      'Juego de Beber',
      'Lima',
      'Limón',
      'Loco',
      'Luces de Colores',
      'Mariachi',
      'Máscara',
      'Mesas',
      'Mezcal',
      'Michelada',
      'Mirrorball',
      'Mocktail',
      'Mojito',
      'Música en Vivo',
      'Noche Buena',
      'Open Bar',
      'Peda',
      'Pinta',
      'Pirotecnia',
      'Piscina',
      'Poker',
      'Pool Party',
      'Posada',
      'Pregunta Maldita',
      'Pub',
      'Quinceañera',
      'Rondas',
      'Ruleta',
      'Sangría',
      'Selfie',
      'Serpentina',
      'Sidra',
      'Sonidero',
      'Sorpresa',
      'Tablero de Juegos',
      'Tarima',
      'Terrazo',
      'Terraza',
      'Tonel',
      'Tostada',
      'Tragos',
      'Trago Doble',
      'Trago Triple',
      'Tubo',
      'Tuno',
      'Turno',
      'Xolos',
      'Abrir Barra',
      'Afterhours',
      'Animación',
      'Antifaz',
      'Arranque',
      'Asado',
      'Bailarina',
      'Bandeja',
      'Barra',
      'Bebida de Cortesía',
      'Bienvenida',
      'Birra',
      'Botella Magnum',
      'Caipirinha',
      'Cantinero',
      'Catering',
      'Cerveza Fría',
      'Chupito',
      'Club',
      'Comida Rápida',
      'Cuota',
      'Dj Set',
      'Duelo de Karaoke',
      'Encendedor',
      'Energizante',
      'Entrada',
      'Espumoso',
      'Exceso',
      'Famoso',
      'Festival',
      'Fiesta Clandestina',
      'Fiesta en la Alberca',
      'Flores de Mesa',
      'Foto de Grupo',
      'Fotomatón',
      'Garrafón',
      'Gritos',
      'Guirnalda',
      'Inauguración',
      'Inflable',
      'Invitado Especial',
      'Juego de Mesa',
      'Keg Stand',
      'Limosina',
      'Lista de Reproducción',
      'Lounge',
      'Luz Negra',
      'Madrugada',
      'Maestro de Ceremonias',
      'Margarita',
      'Memoria',
      'Moscatel',
      'Música Electrónica',
      'Noche de Juegos',
      'Pachanga',
      'Palco',
      'Palomazo',
      'Payaso',
      'Presentador',
      'Reservación',
      'Reunión',
      'Ridículo',
      'Sábado',
      'Sala Privada',
      'Sensación',
      'Servicio',
      'Sponso',
      'Susurro',
      'Table Dance',
      'Tambor',
      'Tarima',
      'Terraza VIP',
      'Toalla',
      'Toga',
      'Tornamesa',
      'Trío',
      'Último Turno',
      'Vendedor',
      'Animación de Fiestas',
      'Bamboleo',
      'Botellazo',
      'Brindis Final',
      'Cachondeo',
      'Cantina Móvil',
      'Carpa',
      'Cohete de Confeti',
      'Copa de Cristal',
      'Cotillón de Año Nuevo',
      'Danza Folklórica',
      'Desfase',
      'Discoteca Móvil',
      'DJ Invitado',
      'Euforia Total',
      'Farra',
      'Fiestazo',
      'Fondo de Pantalla',
      'Gira',
      'Gran Final',
      'Griterío',
      'Grupo de Amigos',
      'Hype',
      'Iluminación',
      'Jolgorio',
      'Juegos de Mesa',
      'Loco de Fiesta',
      'Luces Estroboscópicas',
      'Madrugonazo',
      'Mezclazo',
      'Moleón',
      'Noche de Brujas',
      'Pachangón',
      'Padrino de Boda',
      'Palomazo',
      'Parto',
      'Pasón',
      'Perrero',
      'Pisto',
      'Porras',
      'Premios',
      'Quema de Año Viejo',
      'Reguetón',
      'Revuelta',
      'Selfie de Grupo',
      'Sexteto',
      'Sorpresón',
      'Taconazo',
      'Tarde de Tragos',
      'Templete',
      'Tianguis',
      'Anfitrión',
      'Borrachera Colectiva',
      'Coreografía de Grupo',
      'Escándalo',
      'Fiesta Privada',
      'Guardarropa',
    ],
  ),
  const Category(
    id: 'cine',
    name: 'Cine',
    icon: '🎬',
    color: Colors.blue,
    words: [
      'Acción',
      'Actor',
      'Alfombra Roja',
      'Alien',
      'Anime',
      'Cámara',
      'Cine Mudo',
      'Comedia',
      'Director',
      'Documental',
      'Efectos Especiales',
      'Guion',
      'Hollywood',
      'Oscar',
      'Palomitas',
      'Terror',
      'Taquilla',
      'Tráiler',
      'Villano',
      'Protagonista',
      'Doble de Riesgo',
      'Maquillaje',
      'Vestuario',
      'Pantalla Verde',
      'Secuela',
      'Trilogía',
      'Claquet',
      'Cortometraje',
      'Animación',
      'Musical',
      'Aclamado',
      'Actuación',
      'Adaptación',
      'Agente',
      'Alquiler',
      'Animatrónico',
      'Antagonista',
      'Audiencia',
      'Autobiografía',
      'Biopic',
      'Blockbuster',
      'Bomba de Taquilla',
      'Cameo',
      'Casting',
      'CGI',
      'Ciencia Ficción',
      'Cinematografía',
      'Cinéfilo',
      'Clásico',
      'Club de Fans',
      'Código Hays',
      'Colorización',
      'Comedia Romántica',
      'Concurso',
      'Continuidad',
      'Créditos',
      'Crítica',
      'Doblaje',
      'Drama',
      'Edición',
      'Elenco',
      'Estreno',
      'Fantasía',
      'Festival',
      'Flashback',
      'Formato IMAX',
      'Fotograma',
      'Franquicia',
      'Gangster',
      'Género',
      'Gore',
      'Guionista',
      'Historia',
      'Indie',
      'Largometraje',
      'Lente',
      'Melodrama',
      'Metraje',
      'Montaje',
      'Multiverso',
      'Narración',
      'Nominación',
      'Pantalla',
      'Pase de Prensa',
      'Película de Culto',
      'Percepción',
      'Plot Twist',
      'Postproducción',
      'Premiere',
      'Premio',
      'Producción',
      'Productora',
      'Proyector',
      'Remake',
      'Reparto',
      'Reseña',
      'Rodaje',
      'Sala de Cine',
      'Soundtrack',
      'Spin-off',
      'Spoiler',
      'Suspenso',
      'Tecnología',
      'Telón',
      'Thriller',
      'Transmisión',
      'Unboxing',
      'Western',
      'Widescreen',
      'Zoom',
      'Antihéroe',
      'Arco Narrativo',
      'Auteur',
      'Backstory',
      'Box Set',
      'Audición',
      'Personaje',
      'Director de Fotografía',
      'Cliffhanger',
      'Primer Plano',
      'Corrección de Color',
      'Alivio Cómico',
      'Conflicto',
      'Grúa',
      'Corte Rápido',
      'Comedia Oscura',
      'Escena de Muerte',
      'Desenlace',
      'Diálogo',
      'Sonido Diegético',
      'Cine Negro',
      'Imagen Congelada',
      'Fusión de Géneros',
      'Grip',
      'Cámara en Mano',
      'Incidente Inicial',
      'Salto de Corte',
      'Conteo de Muertes',
      'Iluminación',
      'Reconocimiento de Locación',
      'MacGuffin',
      'Metáfora',
      'Falso Documental',
      'Monólogo',
      'Dilema Moral',
      'Plano General',
      'Edición Paralela',
      'Armadura de Trama',
      'Efecto Práctico',
      'Utilería',
      'Pista Falsa',
      'Acción Creciente',
      'Transición',
      'Diseño de Escenario',
      'Show Runner',
      'Cámara Lenta',
      'Suplente',
      'Material de Archivo',
      'Simbolismo',
      'Lapso de Tiempo',
      'Dos Tomas',
      'Voz en Off',
      'Bloqueo de Escena',
      'Retorno',
      'Catarsis',
      'Escena de Persecución',
      'Clímax',
      'Apertura en Frío',
      'Paleta de Colores',
      'Coreografía de Combate',
      'Corte Cruzado',
      'Escena Multitudinaria',
      'Decepción',
      'Disolvencia',
      'Ángulo Inclinado',
      'Elipsis',
      'Elenco de Conjunto',
      'Plano de Establecimiento',
      'Exposición',
      'Presagio',
      'Cuarta Pared',
      'Escritor Fantasma',
      'Hora Dorada',
      'Plano Heroico',
      'Ángulo Alto',
      'Homenaje',
      'Giro de Identidad',
      'Intercalación',
      'Iris',
      'Yuxtaposición',
      'Conteo de Bajas',
      'Ángulo Bajo',
      'Corte Combinado',
      'Escena de Recuerdo',
      'Escena de En Medio de los Créditos',
      'Escena de Espejo',
      'Desvío de Atención',
      'Visión Nocturna',
      'Secuencia de Apertura',
      'Historia de Origen',
      'Plano Cenital',
      'Panorámica',
      'Perspectiva',
      'Punto de Giro',
      'Punto de Vista',
      'Escena Post-Créditos',
      'Plano de Poder',
      'Perfil',
      'Prólogo',
      'Reinicio',
      'Arco de Redención',
      'Revelación',
      'Contraplano',
      'Rebobinar',
      'Robo de Escena',
      'Plano del Horizonte',
      'Avance',
      'Storyboard',
      'Subtrama',
      'Final Sorpresa',
      'Reloj en Cuenta Regresiva',
      'Tarjeta de Título',
      'Final con Giro',
      'Apertura del Acto',
      'Personaje Secundario',
      'Guion Original',
      'Escenas Eliminadas',
      'Director de Casting',
      'Épico',
      'Estética Visual',
      'Fracaso de Taquilla',
      'Héroe Improbable',
      'Identidad Oculta',
      'Jornada del Héroe',
      'Liga de Fans',
      'Momento de Revelación',
      'Narrador No Confiable',
      'Oscilación de Ánimo',
      'Parodia',
      'Personaje de Apoyo',
      'Precuela',
      'Presupuesto de Producción',
      'Reacción del Público',
      'Secuencia de Acción',
      'Show de Temporada',
      'Universo Cinematográfico',
      'Antagonista Principal',
      'Cámara Subjetiva',
      'Efecto Dominó',
      'Escena Icónica',
    ],
  ),
  const Category(
    id: 'comida',
    name: 'Comida',
    icon: '🌮',
    color: Colors.orange,
    words: [
      'Aguacate',
      'Alitas',
      'Arroz',
      'Tocino',
      'Burrito',
      'Café',
      'Cereal',
      'Chocolate',
      'Hamburguesa',
      'Helado',
      'Hot Dog',
      'Pizza',
      'Sushi',
      'Tacos',
      'Tamales',
      'Espagueti',
      'Queso',
      'Ensalada',
      'Sopa',
      'Pan',
      'Mantequilla',
      'Galleta',
      'Pastel',
      'Dona',
      'Waffle',
      'Crepa',
      'Sandwich',
      'Kétchup',
      'Mostaza',
      'Mayonesa',
      'Papas Fritas',
      'Acelgas',
      'Agua de Jamaica',
      'Ahumado',
      'Ajo',
      'Albóndigas',
      'Almedras',
      'Anchoa',
      'Atún',
      'Barbacoa',
      'Berberecho',
      'Birria',
      'Bizcocho',
      'Bolillo',
      'Burritos',
      'Cacahuate',
      'Caldo',
      'Camarones',
      'Carnitas',
      'Cazuela',
      'Ceviche',
      'Chalupa',
      'Champurrado',
      'Chicharrón',
      'Chile',
      'Chilaquiles',
      'Chorizos',
      'Churros',
      'Cochinita Pibil',
      'Coco',
      'Codorniz',
      'Consome',
      'Corunda',
      'Costillas',
      'Crema',
      'Croquetas',
      'Deditos',
      'Discada',
      'Ejotes',
      'Elote',
      'Empanada',
      'Enchilada',
      'Enfrijolada',
      'Entomatada',
      'Esquites',
      'Estofado',
      'Fajitas',
      'Flautas',
      'Flan',
      'Fondue',
      'Fresas',
      'Frijoles',
      'Frutas',
      'Gazpacho',
      'Gelatina',
      'Gordita',
      'Gravy',
      'Guacamole',
      'Guisado',
      'Harina',
      'Huevos',
      'Hummus',
      'Jamón',
      'Jarritos',
      'Jitomate',
      'Lasaña',
      'Leche',
      'Lechuga',
      'Lentejas',
      'Limonada',
      'Lomo',
      'Maíz',
      'Mango',
      'Marisco',
      'Memela',
      'Menudo',
      'Milanesa',
      'Mole',
      'Naranja',
      'Nieve',
      'Nopal',
      'Nuggets',
      'Pachola',
      'Paella',
      'Paleta',
      'Palmito',
      'Papaya',
      'Pasta',
      'Pay',
      'Pepino',
      'Pibil',
      'Piña',
      'Pollo',
      'Pozole',
      'Pulpo',
      'Quesadilla',
      'Queso Fundido',
      'Res',
      'Relleno',
      'Risotto',
      'Salchicha',
      'Salsa',
      'Sandia',
      'Sincronizada',
      'Sobre Barriga',
      'Taco de Canasta',
      'Tapioca',
      'Tarta',
      'Tasajo',
      'Tlayuda',
      'Torta',
      'Tortilla',
      'Tostada',
      'Uvas',
      'Verdolagas',
      'Zanahoria',
      'Adobo',
      'Aguachile',
      'Albahaca',
      'Alcachofa',
      'Alubias',
      'Arepas',
      'Atole',
      'Avena',
      'Azafrán',
      'Berros',
      'Betabel',
      'Bolillos',
      'Buñuelos',
      'Cabrito',
      'Calabaza',
      'Caldillo',
      'Canela',
      'Capirotada',
      'Caramelo',
      'Cardamomo',
      'Cazuelitas',
      'Cebolla',
      'Cecina',
      'Chilorio',
      'Clemole',
      'Comino',
      'Cordero',
      'Cuachala',
      'Curtido',
      'Duraznos',
      'Ejotes',
      'Epazote',
      'Escabeche',
      'Espinacas',
      'Estofado',
      'Fiambre',
      'Fruta de Temporada',
      'Garbanzo',
      'Gorditas de Maíz',
      'Guajolote',
      'Guava',
      'Higo',
      'Hojas de Plátano',
      'Huarache',
      'Injerto',
      'Itacate',
      'Jericalla',
      'Jitomate Cherry',
      'Jugo Verde',
      'Machaca',
      'Mandarina',
      'Manteca',
      'Mariscos',
      'Masa',
      'Membrillo',
      'Mermelada',
      'Miel',
      'Molcajete',
      'Moronga',
      'Muslo de Pollo',
      'Nata',
      'Nopales',
      'Orégano',
      'Papalotes',
      'Pepita',
      'Perejil',
      'Pimienta',
      'Plátano',
      'Pollo en Mole',
      'Ponche',
      'Puerco',
      'Pulque',
      'Rajas',
      'Romeritos',
      'Salpicón',
      'Salmón',
      'Semillas',
      'Silabario',
      'Sincronizada',
      'Sopa Azteca',
      'Sopes',
      'Tamal de Rajas',
      'Tejate',
      'Tepache',
      'Tinga',
      'Uchepo',
      'Vainilla',
      'Vinagre',
      'Xoconostle',
      'Yerba Buena',
      'Zacahuil',
      'Achicoria',
      'Aguamiel',
      'Amaranto',
      'Apio',
      'Arroz con Leche',
      'Arroz con Pollo',
      'Azúcar',
      'Calabacita',
      'Camote',
      'Cilantro',
      'Codillo',
      'Colorines',
      'Dulce de Leche',
      'Escamoles',
      'Flor de Calabaza',
      'Gusanos de Maguey',
    ],
  ),
  const Category(
    id: 'lugares',
    name: 'Lugares',
    icon: '🌍',
    color: Colors.teal,
    words: [
      'Aeropuerto',
      'Banco',
      'Biblioteca',
      'Bosque',
      'Cantina',
      'Cárcel',
      'Castillo',
      'Cementerio',
      'Cine',
      'Circo',
      'Desierto',
      'Escuela',
      'Espacio',
      'Estadio',
      'Farmacia',
      'Gimnasio',
      'Hospital',
      'Hotel',
      'Isla',
      'Laboratorio',
      'Luna',
      'Marte',
      'Mina',
      'Museo',
      'Océano',
      'Parque',
      'Playa',
      'Restaurante',
      'Selva',
      'Supermercado',
      'Teatro',
      'Torre de Control',
      'Túnel',
      'Universidad',
      'Veterinaria',
      'Volcán',
      'Zoológico',
      'Acuario',
      'Aldea',
      'Almacén',
      'Antártida',
      'Ático',
      'Autopista',
      'Balneario',
      'Barrio',
      'Bodega',
      'Bunker Secreto',
      'Burdel',
      'Callejón',
      'Campo de Guerra',
      'Campo Minado',
      'Canal de Panamá',
      'Caverna',
      'Central Nuclear',
      'Centro Comercial',
      'Ciudad Fantasma',
      'Club Nocturno',
      'Coliseo',
      'Comarca',
      'Comisaría',
      'Consulado',
      'Convento',
      'Crucero',
      'Cueva Marina',
      'Depósito',
      'Embajada',
      'Fábrica',
      'Faro',
      'Favela',
      'Fosa Oceánica',
      'Gasolinera',
      'Glaciar',
      'Gran Muralla',
      'Granja',
      'Guarida',
      'Iglesia',
      'Jungla',
      'Lago',
      'Laguna',
      'Llanura',
      'Mazmorra',
      'Mercado Negro',
      'Monasterio',
      'Monte Everest',
      'Montaña',
      'Morgue',
      'Muralla Medieval',
      'Nave Espacial',
      'Nevado',
      'Oasis',
      'Observatorio',
      'Olimpo',
      'Palacio',
      'Pantano',
      'Plataforma Petrolera',
      'Pradera',
      'Prisión de Alta Seguridad',
      'Pueblo Fantasma',
      'Puerto',
      'Refugio',
      'Río',
      'Rascacielos',
      'Ruinas',
      'Sabana',
      'Sala de Emergencias',
      'Sala de Juegos',
      'Santuario',
      'Submarino',
      'Templo Maya',
      'Torre Eiffel',
      'Triángulo de las Bermudas',
      'Valle',
      'Vertedero',
      'Zona de Guerra',
      'Zona Radioactiva',
      'Ártico',
      'Bambusal',
      'Bayou',
      'Cañón',
      'Catacumba',
      'Puesto de Control',
      'Acantilado',
      'Centro de Mando',
      'Cráter',
      'Cueva de Cristal',
      'Mar Muerto',
      'Corredor de la Muerte',
      'Portal Dimensional',
      'Muelle',
      'Tundra Helada',
      'Garganta',
      'Gran Cañón',
      'Casa Embrujada',
      'Fortaleza Oculta',
      'Iceberg',
      'Sala de Interrogación',
      'Vertedero',
      'Ciudad Espejismo',
      'Puesto Avanzado',
      'Meseta',
      'Arrecife',
      'Alcantarilla',
      'Naufragio',
      'Estación Espacial',
      'Pantanos',
      'Sala del Trono',
      'Ciudad Subterránea',
      'Cascada',
      'Barranca',
      'Bodega Secreta',
      'Cabina de Control',
      'Campamento Base',
      'Centro de Detención',
      'Ciudadela',
      'Clonario',
      'Complejo Militar',
      'Corredor Infinito',
      'Dársena',
      'Estudio de Grabación',
      'Finca',
      'Fuerte',
      'Galería de Arte',
      'Garita',
      'Gruta',
      'Habitación del Pánico',
      'Hangar',
      'Jardín Botánico',
      'Laberinto de Espejos',
      'Madriguera',
      'Mansión Abandonada',
      'Matadero',
      'Mezquita',
      'Mina de Sal',
      'Muelle Flotante',
      'Nave Industrial',
      'Palacio de Justicia',
      'Parque Nacional',
      'Pasaje Secreto',
      'Pista de Aterrizaje',
      'Plaza de Toros',
      'Portón',
      'Poblado',
      'Reclusorio',
      'Sala de Máquinas',
      'Sótano',
      'Spa de Lujo',
      'Taberna',
      'Tanque de Entrenamiento',
      'Taquería',
      'Torre de Vigilancia',
      'Trampolín',
      'Trinchera',
      'Uranio',
      'Aeródromo',
      'Alcatraz',
      'Callejón sin Salida',
      'Campo de Entrenamiento',
      'Cancha',
      'Capilla',
      'Celda de Aislamiento',
      'Centro de Rehabilitación',
      'Ciudad Amurallada',
      'Colonia Penal',
      'Complejo Residencial',
      'Corredor Secreto',
      'Estación de Bomberos',
      'Estación de Policía',
      'Estudio de Arquitectura',
      'Explanada',
      'Ferrocarril',
      'Finca Abandonada',
      'Fortaleza Medieval',
      'Frontón',
      'Garita de Control',
      'Isla Desierta',
      'Mansión Señorial',
      'Monte Sagrado',
      'Nido de Águila',
      'Palco de Autoridades',
      'Pasarela',
      'Penitenciaría',
      'Piscina Olímpica',
      'Pozo',
      'Puente Colgante',
      'Rancho',
      'Recinto Ferial',
      'Sede',
      'Terreno Baldío',
      'Tumba',
      'Tunel del Tiempo',
      'Vagón',
      'Zócalo',
      'Albergue',
      'Archipiélago',
      'Bahía',
      'Barranca',
      'Caldera',
      'Campamento',
      'Celda',
      'Centro de Mando',
      'Cueva Submarina',
      'Destilería',
      'Estrecho',
      'Frontera',
      'Hacienda',
      'Isla Volcánica',
      'Kibutz',
      'Lago Glaciar',
      'Madriguera',
      'Manantial',
      'Muralla',
    ],
  ),
  const Category(
    id: 'animales',
    name: 'Animales',
    icon: '🦁',
    color: Colors.green,
    words: [
      'Abeja',
      'Águila',
      'Ajolote',
      'Alce',
      'Araña',
      'Ardilla',
      'Armadillo',
      'Avestruz',
      'Ballena',
      'Búho',
      'Burro',
      'Caballo',
      'Cabra',
      'Camello',
      'Cangrejo',
      'Canguro',
      'Capibara',
      'Castor',
      'Cebra',
      'Cerdo',
      'Chango',
      'Chita',
      'Cisne',
      'Cocodrilo',
      'Colibrí',
      'Conejo',
      'Coyote',
      'Delfín',
      'Elefante',
      'Escorpión',
      'Flamenco',
      'Foca',
      'Gallina',
      'Gato',
      'Gorila',
      'Grillo',
      'Gusano',
      'Hámster',
      'Hipopótamo',
      'Hormiga',
      'Hurón',
      'Iguana',
      'Jaguar',
      'Jirafa',
      'Koala',
      'León',
      'Lobo',
      'Loro',
      'Mariposa',
      'Murciélago',
      'Oso',
      'Paloma',
      'Pato',
      'Pavo',
      'Perro',
      'Pingüino',
      'Pulpo',
      'Rana',
      'Ratón',
      'Rinoceronte',
      'Serpiente',
      'Tiburón',
      'Tigre',
      'Tortuga',
      'Vaca',
      'Zorro',
      'Albatros',
      'Alce Macho',
      'Alpaca',
      'Anaconda',
      'Anguila',
      'Antílope',
      'Arma Rillo',
      'Babosa',
      'Bagre',
      'Barracuda',
      'Bisonte',
      'Boa',
      'Buitre',
      'Búfalo',
      'Caballo Marino',
      'Caracol',
      'Caribú',
      'Castor de Montaña',
      'Caimán',
      'Camaleón',
      'Carpa',
      'Casuar',
      'Cerdo Hormiguero',
      'Ciervo',
      'Cigüeña',
      'Cobra',
      'Colibri Enano',
      'Cóndor',
      'Cormorán',
      'Cuervo',
      'Culebra',
      'Cuscús',
      'Damán',
      'Dugongo',
      'Emú',
      'Erizo',
      'Escarabajo',
      'Estrella de Mar',
      'Faisán',
      'Ferret',
      'Gacela',
      'Galápago',
      'Ganso',
      'Gavial',
      'Gaviota',
      'Gibón',
      'Glotón',
      'Guacamayo',
      'Guanaco',
      'Guepardo',
      'Guppy',
      'Hiena',
      'Ibis',
      'Jacamar',
      'Jabalí',
      'Kiwi',
      'Lagartija',
      'Lamprea',
      'Langosta',
      'Lechuza',
      'Lemur',
      'Leopardo',
      'Liebre',
      'Lince',
      'Llama',
      'Lobo Marino',
      'Lucerna',
      'Manatí',
      'Mandril',
      'Mangosta',
      'Mapache',
      'Marmota',
      'Medusa',
      'Mejillón',
      'Mono Araña',
      'Morsa',
      'Musaraña',
      'Narval',
      'Nutria',
      'Okapi',
      'Orang Utan',
      'Orca',
      'Ostra',
      'Panda',
      'Pantera',
      'Papagayo',
      'Pavo Real',
      'Pelícano',
      'Pereza',
      'Pez Espada',
      'Pez Payaso',
      'Pitón',
      'Polilla',
      'Quetzal',
      'Rata Topo',
      'Raya',
      'Reno',
      'Salamandra',
      'Salmón',
      'Sepia',
      'Serpiente de Cascabel',
      'Tapir',
      'Tejón',
      'Termita',
      'Topo',
      'Tucán',
      'Venado',
      'Víbora',
      'Visón',
      'Wombat',
      'Yak',
      'Zarigüeya',
      'Aligátor',
      'Almeja',
      'Ameba',
      'Armiño',
      'Asno',
      'Atún Rojo',
      'Avispa',
      'Axolote Albino',
      'Babosa de Mar',
      'Bagre de Río',
      'Ballena Azul',
      'Barbo',
      'Bicho Palo',
      'Bisonte Americano',
      'Buitre Negro',
      'Caballo de Mar',
      'Cacatúa',
      'Canario',
      'Cangrejito',
      'Caracal',
      'Carracas',
      'Castor Europeo',
      'Cerdo Espín',
      'Chacal',
      'Chimpancé',
      'Ciervo Rojo',
      'Civeta',
      'Coatí',
      'Cobra Real',
      'Cóndor Andino',
      'Corzo',
      'Cotorra',
      'Dingo',
      'Dragón de Komodo',
      'Dromedario',
      'Dugón',
      'Equidna',
      'Escarabajo Pelotero',
      'Faisán Dorado',
      'Foca Leopardo',
      'Gacela de Thomson',
      'Galgo',
      'Gato Montés',
      'Gavilán',
      'Gecko',
      'Gerifalte',
      'Glotón Ártico',
      'Golondrina',
      'Grulla',
      'Guanaco Patagónico',
      'Halcón Peregrino',
      'Hipocampo',
      'Jabalí Africano',
      'Lagarto Monitor',
      'Lemming',
      'Leopardo de las Nieves',
      'Lince Ibérico',
      'Lobo Etíope',
      'Luciérnaga',
      'Malambo',
      'Mantarraya',
      'Mariposa Monarca',
      'Meerkat',
      'Mono Capuchino',
      'Mono Narigudo',
      'Morralla',
      'Mosca del Tsetse',
      'Nandú',
      'Ornitorrinco',
      'Oso Hormiguero',
      'Oso Panda Rojo',
      'Oso Polar',
      'Panda Gigante',
      'Pato Mandarín',
      'Pato Real',
      'Perezoso de Tres Dedos',
      'Pez Globo',
      'Pez Volador',
      'Pingüino Emperador',
      'Potro',
      'Puerco Espín',
      'Quokka',
      'Rata Canguro',
      'Rinoceronte Blanco',
      'Serpiente Rey',
      'Tapir Amazónico',
      'Tazmanian Devil',
      'Tigre de Bengala',
      'Ualabí',
      'Ñu',
    ],
  ),
];

// ==========================================
// BASE DE DATOS: INGLÉS (~2100 palabras)
// ==========================================
final List<Category> _categoriesEn = [
  const Category(
    id: 'mix',
    name: 'Random',
    icon: '🎲',
    color: Colors.purple,
    words: [
      'Black Hole',
      'Alchemist',
      'Amnesia',
      'Apocalypse',
      'Astronaut',
      'Atom',
      'Avatar',
      'Battery',
      'Bitcoin',
      'Bunker',
      'Knight',
      'Chameleon',
      'Catapult',
      'Cinderella',
      'Centaur',
      'Cyborg',
      'Dinosaur',
      'Dragon',
      'Sphinx',
      'Alien',
      'Ghost',
      'Frankenstein',
      'Genie',
      'Gravity',
      'Spell',
      'Fairy',
      'Hypnosis',
      'Illusion',
      'Karma',
      'Labyrinth',
      'Magic',
      'Mummy',
      'Mutant',
      'Ninja',
      'UFO',
      'Pirate',
      'Portal',
      'Robot',
      'Mermaid',
      'Superhero',
      'Telepathy',
      'Vampire',
      'Viking',
      'Zombie',
      'Alchemy',
      'Amulet',
      'Apocalyptic Rift',
      'Rainbow',
      'Archer',
      'Coffin',
      'Atlantic',
      'Aurora Borealis',
      'Bigfoot',
      'Witch',
      'Witchcraft',
      'Skull',
      'Invisibility Cloak',
      'Time Capsule',
      'Cataclysm',
      'Clone',
      'Secret Code',
      'Comet',
      'Constellation',
      'Kryptonite',
      'Magic Crystal',
      'Cave',
      'Cyber',
      'Deja Vu',
      'Destiny',
      'Dimension',
      'Goddess',
      'Eclipse',
      'Elf',
      'Dwarf',
      'Crossroads',
      'Energy',
      'Enigma',
      'Slave',
      'Mirage',
      'Spy',
      'Spirit',
      'Star',
      'Explosion',
      'Pharaoh',
      'Deadline',
      'Phoenix',
      'Fossil',
      'Gargoyle',
      'Gladiator',
      'Golem',
      'Griffin',
      'Warrior',
      'Hologram',
      'Werewolf',
      'Icarus',
      'Emperor',
      'Thief',
      'Legend',
      'Lantern',
      'Master Key',
      'Master',
      'Fire Butterfly',
      'Matrix',
      'Medusa',
      'Hive Mind',
      'Liar',
      'Meteorite',
      'Minotaur',
      'Mystery',
      'Myth',
      'Morgana',
      'Monk',
      'Nirvana',
      'Oracle',
      'Orc',
      'Darkness',
      'Pegasus',
      'Poltergeist',
      'Poseidon',
      'Prophecy',
      'Prometheus',
      'Chimera',
      'Resurrection',
      'Rex',
      'Ritual',
      'Runes',
      'Samurai',
      'Satellite',
      'Shadow',
      'Sorcery',
      'Subconscious',
      'Talisman',
      'Temple',
      'Time',
      'Titan',
      'Totem',
      'Troll',
      'Tsunami',
      'Unicorn',
      'Parallel Universe',
      'Valkyrie',
      'Warlock',
      'Wormhole',
      'Yeti',
      'Zeus',
      'Zombie Apocalypse',
      'Dead Zone',
      'Abyss',
      'Riddle',
      'Fallen Angel',
      'Anomaly',
      'Antimatter',
      'Secret Weapon',
      'Astral',
      'Aura',
      'Beast',
      'Biomechanical',
      'Chaos',
      'Sentinel',
      'Chakra',
      'Binary Code',
      'Convergence',
      'Magic Crown',
      'Crypt',
      'Power Crystal',
      'Crusade',
      'Healer',
      'Cyberpunk',
      'Daemon',
      'Disappearance',
      'Disintegration',
      'Forgotten God',
      'Dystopia',
      'Divine',
      'Domain',
      'Doppelganger',
      'Enchantment',
      'Swordsman',
      'Specter',
      'Eternal',
      'Ether',
      'Exorcism',
      'Fatality',
      'Dark Force',
      'Galaxy',
      'Dimensional Rift',
      'Guardian',
      'Brotherhood',
      'Heroine',
      'Sandman',
      'Horizon',
      'Icon',
      'Underworld',
      'Interdimensional',
      'Invisibility',
      'Legilimancy',
      'Lich',
      'Mastermind',
      'Metamorphosis',
      'Mirror World',
      'Nectar',
      'Necropolis',
      'Nexus',
      'Necromancer',
      'Nymphs',
      'Eternal Night',
      'Nucleus',
      'Obsidian',
      'Ogre',
      'Omniscient',
      'Onyx',
      'Dark Pact',
      'Paradox',
      'Red Planet',
      'Stardust',
      'Primitive',
      'Fugitive',
      'Reincarnation',
      'Reliquary',
      'Seal',
      'Signal',
      'Simulacrum',
      'Singularity',
      'Underground',
      'Supernovas',
      'Telepathic',
      'Testament',
      'Trap',
      'Transgression',
      'Astral Travel',
      'Vision',
      'Vortex',
      'Cursed Sapphire',
      'Cosmic Anchor',
      'Shadow Armor',
      'Eternal Mist',
      'Fire Waterfall',
      'Time Scar',
      'Code of Honor',
      'Black Quartz',
      'Flash',
      'Pure Essence',
      'Runic Sword',
      'Shapeshifter',
      'Fragment',
      'Grimoire',
      'Seraph',
      'Specter',
      'Void',
      'Wraith',
    ],
  ),
  const Category(
    id: 'fiesta',
    name: 'Party',
    icon: '🍻',
    color: Colors.pink,
    words: [
      'Breathalyzer',
      'Speaker',
      'New Year',
      'Nightclub',
      'Bartender',
      'Wedding',
      'Drunk',
      'Snacks',
      'Beer',
      'Champagne',
      'Concert',
      'Hangover',
      'DJ',
      'Costume',
      'Karaoke',
      'Shot',
      'Piñata',
      'Cake',
      'Balloons',
      'Invitation',
      'Dance',
      'Hangover',
      'Tequila',
      'Vodka',
      'Rum',
      'Wine',
      'Ice',
      'Glass',
      'Toast',
      'Bachelor Party',
      'Confetti',
      'VIP',
      'Wristband',
      'Bouncer',
      'After Party',
      'Entertainer',
      'Open Bar',
      'Barrel',
      'Bottle Service',
      'Bottle',
      'Buffet',
      'Booth',
      'Pub',
      'Carnival',
      'Casino',
      'Celebration',
      'Craft Beer',
      'Cocktail',
      'Firecracker',
      'Cup',
      'Party Favor',
      'Dice Cup',
      'Birthday',
      'Disco',
      'Dressed Up',
      'Drink',
      'Euphoria',
      'Theme Party',
      'Flowers',
      'Bonfire',
      'Fireworks',
      'Gin',
      'Cap',
      'Beer Tap',
      'Band',
      'Happy Hour',
      'Horchata',
      'Pitcher',
      'Drinking Game',
      'Lime',
      'Lemon',
      'Crazy',
      'Colored Lights',
      'Band',
      'Mask',
      'Tables',
      'Mezcal',
      'Michelada',
      'Mirrorball',
      'Mocktail',
      'Mojito',
      'Live Music',
      'Christmas Eve',
      'Open Bar',
      'Pub Crawl',
      'Pint',
      'Pyrotechnics',
      'Pool',
      'Poker',
      'Pool Party',
      'Posada',
      'Truth or Dare',
      'Pub',
      'Quinceanera',
      'Rounds',
      'Roulette',
      'Sangria',
      'Selfie',
      'Streamer',
      'Cider',
      'Sound System',
      'Surprise',
      'Board Game',
      'Stage',
      'Terrace',
      'Rooftop',
      'Keg',
      'Drinks',
      'Double Shot',
      'Triple Shot',
      'Tube Shot',
      'Bachelorette',
      'Jello Shot',
      'Flip Cup',
      'Beer Pong',
      'Cheers',
      'Conga Line',
      'Flash Mob',
      'Glow Stick',
      'Photobooth',
      'Playlist',
      'RSVP',
      'Toga Party',
      'Trivia Night',
      'Afterhours',
      'Animator',
      'Bachelorette Party',
      'Bandana',
      'Bar Tab',
      'Bartending',
      'Bash',
      'Blowout',
      'Body Paint',
      'Bouncy Castle',
      'Catering',
      'Celebration',
      'Charades',
      'Chug',
      'Club Night',
      'Cold Beer',
      'Countdown',
      'Craft Cocktail',
      'Dance Floor',
      'Darts',
      'Day Party',
      'Disco Ball',
      'Door Prize',
      'Dress Code',
      'Electric Slide',
      'Encore',
      'Event Planner',
      'Face Painting',
      'Fake ID',
      'Fancy Dress',
      'Foam Party',
      'Fondue',
      'Free Admission',
      'Function',
      'Game Night',
      'Gathering',
      'Guestlist',
      'Hotdog Stand',
      'House Party',
      'Icebreaker',
      'Instagrammable',
      'Jukebox',
      'Karaoke Mic',
      'Keg Party',
      'Limo Ride',
      'Live Band',
      'Lock In',
      'Long Island',
      'Margarita',
      'Midnight',
      'Mixer',
      'Moonshine',
      'Murder Mystery',
      'Neon Light',
      'Night Cap',
      'Nightlife',
      'Novelty Hat',
      'Open Mic',
      'Party Bus',
      'Party Favor',
      'Party Horn',
      'Party Planning',
      'Punchline',
      'Rave',
      'Reunion',
      'Scavenger Hunt',
      'Shaker',
      'Sip and Paint',
      'Slumber Party',
      'Sparkling Water',
      'Spirits',
      'Spritzer',
      'Stag Do',
      'Stomping Ground',
      'Street Party',
      'Tailgate',
      'Tea Party',
      'Tiki Bar',
      'Tipsy',
      'Ugly Sweater',
      'Vibe',
      'Whiskey',
      'Wig',
      'Yard',
      'Zero Proof',
      'Arcade Games',
      'Baby Shower',
      'Bartender Tips',
      'Blackout Curtains',
      'Block Party',
      'Brunch Party',
      'Carpool Karaoke',
      'Celebration Cake',
      'Clinking Glasses',
      'Cocktail Hour',
      'Cold Brew',
      'Comedy Night',
      'Costume Contest',
      'Cover Charge',
      'Dance Battle',
      'Designated Driver',
      'Dinner Party',
      'Drinking Straw',
      'Float',
      'Fun Zone',
      'Game Host',
      'Gift Exchange',
      'Grand Opening',
      'Guest of Honor',
      'Hat Party',
      'Holiday Party',
      'Ice Breaker Game',
      'In-house DJ',
      'Juice Bar',
      'Lanyard',
      'Luau',
      'Mardi Gras',
      'Mingle',
      'Mocktail Bar',
      'Music Festival',
      'Night Owl',
      'Party Crasher',
      'Photo Op',
      'Pool Noodle',
      'Pub Quiz',
      'Red Solo Cup',
      'Road Trip Party',
      'Sash',
      'Secret Santa',
      'Sleepover',
      'Social Hour',
      'Sparkling Juice',
      'Spin the Bottle',
      'Themed Drinks',
      'Tiara',
    ],
  ),
  const Category(
    id: 'cine',
    name: 'Movies',
    icon: '🎬',
    color: Colors.blue,
    words: [
      'Action',
      'Actor',
      'Red Carpet',
      'Alien',
      'Anime',
      'Camera',
      'Silent Film',
      'Comedy',
      'Director',
      'Documentary',
      'Special Effects',
      'Script',
      'Hollywood',
      'Oscar',
      'Popcorn',
      'Horror',
      'Box Office',
      'Trailer',
      'Villain',
      'Protagonist',
      'Stunt Double',
      'Makeup',
      'Wardrobe',
      'Green Screen',
      'Sequel',
      'Trilogy',
      'Clapperboard',
      'Short Film',
      'Animation',
      'Musical',
      'Acclaimed',
      'Performance',
      'Adaptation',
      'Agent',
      'Rental',
      'Animatronic',
      'Antagonist',
      'Audience',
      'Autobiography',
      'Biopic',
      'Blockbuster',
      'Bomb',
      'Cameo',
      'Casting',
      'CGI',
      'Science Fiction',
      'Cinematography',
      'Film Buff',
      'Classic',
      'Fan Club',
      'Hays Code',
      'Colorization',
      'Romantic Comedy',
      'Competition',
      'Continuity',
      'Credits',
      'Review',
      'Dubbing',
      'Drama',
      'Editing',
      'Cast',
      'Premiere',
      'Fantasy',
      'Festival',
      'Flashback',
      'IMAX',
      'Frame',
      'Franchise',
      'Gangster',
      'Genre',
      'Gore',
      'Screenwriter',
      'Story',
      'Indie',
      'Feature Film',
      'Lens',
      'Melodrama',
      'Footage',
      'Montage',
      'Multiverse',
      'Narration',
      'Nomination',
      'Screen',
      'Press Screening',
      'Cult Film',
      'Perception',
      'Plot Twist',
      'Post-production',
      'Award',
      'Production',
      'Studio',
      'Projector',
      'Remake',
      'Cast',
      'Rating',
      'Filming',
      'Movie Theater',
      'Soundtrack',
      'Spin-off',
      'Spoiler',
      'Suspense',
      'Technology',
      'Curtain',
      'Thriller',
      'Streaming',
      'Unboxing',
      'Western',
      'Widescreen',
      'Zoom',
      'Antihero',
      'Arc',
      'Auteur',
      'Backstory',
      'Bomb Threat',
      'Box Set',
      'Casting Call',
      'Character',
      'Cinematographer',
      'Cliffhanger',
      'Close-up',
      'Color Grading',
      'Comic Relief',
      'Conflict',
      'Crane Shot',
      'Cutaway',
      'Dark Comedy',
      'Deadline',
      'Death Scene',
      'Denouement',
      'Dialogue',
      'Diegetic Sound',
      'Film Noir',
      'Freeze Frame',
      'Genre Blend',
      'Grip',
      'Handheld Shot',
      'Inciting Incident',
      'Jump Cut',
      'Kill Count',
      'Lighting',
      'Location Scout',
      'MacGuffin',
      'Metaphor',
      'Mockumentary',
      'Monologue',
      'Moral Dilemma',
      'Pan Shot',
      'Parallel Editing',
      'Plot Armor',
      'Practical Effect',
      'Prop',
      'Red Herring',
      'Rising Action',
      'Scene Transition',
      'Set Design',
      'Show Runner',
      'Slow Motion',
      'Stand-in',
      'Stock Footage',
      'Symbolism',
      'Time Lapse',
      'Two-shot',
      'Voice-over',
      'Blocking',
      'Callback',
      'Catharsis',
      'Chase Scene',
      'Climax',
      'Cold Open',
      'Color Palette',
      'Combat Choreography',
      'Crosscutting',
      'Crowd Scene',
      'Daylight Scene',
      'Deception',
      'Dissolve Cut',
      'Dutch Angle',
      'Ellipsis',
      'Ensemble Cast',
      'Establishing Shot',
      'Exposition',
      'Foreshadowing',
      'Fourth Wall',
      'Ghost Writer',
      'Golden Hour',
      'Hero Shot',
      'High Angle',
      'Homage',
      'Identity Twist',
      'Intercut',
      'Iris Shot',
      'Juxtaposition',
      'Kill Shot',
      'Low Angle',
      'Match Cut',
      'Memory Scene',
      'Mid-credits Scene',
      'Mirror Scene',
      'Misdirection',
      'Night Vision',
      'Opening Sequence',
      'Origin Story',
      'Overhead Shot',
      'Pan',
      'Perspective',
      'Pivot Point',
      'Point of View',
      'Post-credits Scene',
      'Power Shot',
      'Profile Shot',
      'Prologue',
      'Reboot',
      'Redemption Arc',
      'Revelation',
      'Reverse Shot',
      'Rewind',
      'Scene Steal',
      'Skyline Shot',
      'Sneak Peek',
      'Storyboard',
      'Subplot',
      'Surprise Ending',
      'Ticking Clock',
      'Title Card',
      'Twist Ending',
      'Act Break',
      'Aerial Shot',
      'B-Roll',
      'Backstage',
      'Behind the Scenes',
      'Character Study',
      'Cinematic Universe',
      'Continuity Error',
      'Crowd Reaction',
      'Death Fake-out',
      'Director Cut',
      'Dollly Shot',
      'Down Angle',
      'Emotional Score',
      'End Credits',
      'Enemy Reveal',
      'Ensemble Piece',
      'Epic Battle',
      'Fan Theory',
      'Forbidden Love',
      'Franchise Builder',
      'Hero Journey',
      'Hidden Clue',
      'Iconic Quote',
      'Ironic Ending',
      'Key Scene',
      'Love Interest',
      'Mask Off',
      'Meta Humor',
      'Miniseries',
      'Missing Scene',
      'Mood Shift',
      'Origin Flashback',
      'Pilot Episode',
      'Power Theme',
      'Prequel',
      'Ratings Bomb',
      'Redemption Scene',
      'Reveal Moment',
      'Reveal Shot',
      'Rule of Three',
      'Score Build',
      'Secret Identity',
      'Sequel Hook',
      'Setup and Payoff',
    ],
  ),
  const Category(
    id: 'comida',
    name: 'Food',
    icon: '🌮',
    color: Colors.orange,
    words: [
      'Avocado',
      'Wings',
      'Rice',
      'Bacon',
      'Burrito',
      'Coffee',
      'Cereal',
      'Chocolate',
      'Hamburger',
      'Ice Cream',
      'Hot Dog',
      'Pizza',
      'Sushi',
      'Tacos',
      'Tamales',
      'Spaghetti',
      'Cheese',
      'Salad',
      'Soup',
      'Bread',
      'Butter',
      'Cookie',
      'Cake',
      'Donut',
      'Waffle',
      'Crepe',
      'Sandwich',
      'Ketchup',
      'Mustard',
      'Mayonnaise',
      'French Fries',
      'Alfredo',
      'Almond',
      'Anchovy',
      'Apple',
      'Artichoke',
      'Asparagus',
      'Baguette',
      'Banana',
      'Barbecue',
      'Beef',
      'Beet',
      'Bell Pepper',
      'Biscuit',
      'Black Bean',
      'Blueberry',
      'Bologna',
      'Broccoli',
      'Brownie',
      'Brussels Sprout',
      'Burrata',
      'Butterscotch',
      'Ceviche',
      'Cheesecake',
      'Cherry',
      'Chicken',
      'Chickpea',
      'Chili',
      'Chimichurri',
      'Chips',
      'Chorizo',
      'Cinnamon Roll',
      'Clam',
      'Coconut',
      'Cod',
      'Corn',
      'Crab',
      'Cranberry',
      'Crouton',
      'Cucumber',
      'Curry',
      'Egg',
      'Eggplant',
      'Enchilada',
      'Escargot',
      'Fajita',
      'Feta',
      'Fig',
      'Flatbread',
      'Flan',
      'Garlic',
      'Gelatin',
      'Ginger',
      'Granola',
      'Grape',
      'Gravy',
      'Guacamole',
      'Halloumi',
      'Ham',
      'Hash Brown',
      'Honey',
      'Hummus',
      'Jalapeno',
      'Jam',
      'Jerky',
      'Kale',
      'Kimchi',
      'Lamb',
      'Lasagna',
      'Lemon',
      'Lemonade',
      'Lettuce',
      'Lobster',
      'Lollipop',
      'Macaroni',
      'Mango',
      'Meatball',
      'Melon',
      'Milk',
      'Milkshake',
      'Miso',
      'Mozzarella',
      'Muffin',
      'Mushroom',
      'Mussel',
      'Nacho',
      'Noodle',
      'Oatmeal',
      'Olive',
      'Omelet',
      'Onion',
      'Orange',
      'Oyster',
      'Pancake',
      'Paprika',
      'Parmesan',
      'Pasta',
      'Peach',
      'Peanut Butter',
      'Pear',
      'Pecan',
      'Pepper',
      'Pesto',
      'Pickles',
      'Pie',
      'Pineapple',
      'Pistachio',
      'Pita',
      'Plum',
      'Poached Egg',
      'Polenta',
      'Pomegranate',
      'Pork',
      'Pot Roast',
      'Potato',
      'Pretzel',
      'Prosciutto',
      'Pudding',
      'Pumpkin',
      'Quesadilla',
      'Quinoa',
      'Ramen',
      'Raspberry',
      'Ravioli',
      'Rib',
      'Risotto',
      'Rosemary',
      'Saffron',
      'Salmon',
      'Salsa',
      'Salt',
      'Sausage',
      'Scallop',
      'Shrimp',
      'Smoothie',
      'Spinach',
      'Sriracha',
      'Steak',
      'Strawberry',
      'Swordfish',
      'Syrup',
      'Tiramisu',
      'Toast',
      'Tofu',
      'Tomato',
      'Tortilla',
      'Truffle',
      'Tuna',
      'Turkey',
      'Tzatziki',
      'Vanilla',
      'Vinegar',
      'Watermelon',
      'Yogurt',
      'Zucchini',
      'Acai',
      'Aioli',
      'Antipasto',
      'Arancini',
      'Arugula',
      'Baba Ganoush',
      'Baklava',
      'Balsamic',
      'Bean Dip',
      'Beef Jerky',
      'Beet Salad',
      'Birria',
      'Bone Broth',
      'Buffalo Sauce',
      'Bun',
      'Cannoli',
      'Caramel',
      'Carbonara',
      'Carpaccio',
      'Cassava',
      'Cevapi',
      'Chai',
      'Charcuterie',
      'Cheese Board',
      'Chicken Tikka',
      'Chowder',
      'Ciabatta',
      'Cinnamon',
      'Clam Chowder',
      'Cobbler',
      'Couscous',
      'Creme Brulee',
      'Crumble',
      'Daiquiri',
      'Deviled Egg',
      'Dim Sum',
      'Dragon Fruit',
      'Dressing',
      'Dumplings',
      'Edamame',
      'Empanada',
      'Energy Bar',
      'Escargot',
      'Falafel',
      'Fish Taco',
      'Flatbread',
      'Frittata',
      'Frosting',
      'Fruit Salad',
      'Fudge',
      'Gnocchi',
      'Guava',
      'Gyoza',
      'Herb',
      'Jackfruit',
      'Jerk Chicken',
      'Kafta',
      'Katsu',
      'Kebab',
      'Key Lime Pie',
      'Kolache',
      'Kung Pao',
      'Lychee',
      'Mac and Cheese',
      'Mahi Mahi',
      'Matcha',
      'Meatloaf',
      'Meringue',
      'Minestrone',
      'Mocha',
      'Naan',
      'Nachos',
      'Nori',
      'Pad Thai',
      'Pastrami',
      'Patty Melt',
      'Pho',
      'Pita Bread',
      'Plantain',
      'Poi',
      'Pomelo',
      'Pork Belly',
      'Pound Cake',
      'Prawn',
      'Puff Pastry',
      'Pupusa',
      'Ratatouille',
      'Red Velvet',
      'Remoulade',
      'Ribeye',
      'Ricotta',
      'S\'mores',
      'Samosa',
      'Satay',
      'Scone',
      'Seaweed',
      'Shakshuka',
      'Shawarma',
      'Short Rib',
      'Skewer',
      'Slider',
      'Smoothie Bowl',
      'Sourdough',
      'Spam',
      'Spring Roll',
      'Strudel',
      'Sweet Potato',
      'Tater Tot',
      'Tempura',
      'Tenderloin',
      'Teriyaki',
      'Tres Leches',
      'Truffle Fries',
      'Walnut',
      'Whipped Cream',
    ],
  ),
  const Category(
    id: 'lugares',
    name: 'Places',
    icon: '🌍',
    color: Colors.teal,
    words: [
      'Airport',
      'Bank',
      'Library',
      'Forest',
      'Pub',
      'Prison',
      'Castle',
      'Cemetery',
      'Cinema',
      'Circus',
      'Desert',
      'School',
      'Space',
      'Stadium',
      'Pharmacy',
      'Gym',
      'Hospital',
      'Hotel',
      'Island',
      'Laboratory',
      'Moon',
      'Mars',
      'Mine',
      'Museum',
      'Ocean',
      'Park',
      'Beach',
      'Restaurant',
      'Jungle',
      'Supermarket',
      'Theater',
      'Control Tower',
      'Tunnel',
      'University',
      'Vet',
      'Volcano',
      'Zoo',
      'Aquarium',
      'Village',
      'Warehouse',
      'Antarctica',
      'Attic',
      'Highway',
      'Spa',
      'Neighborhood',
      'Wine Cellar',
      'Secret Bunker',
      'Brothel',
      'Alley',
      'Warzone',
      'Minefield',
      'Panama Canal',
      'Cavern',
      'Nuclear Plant',
      'Mall',
      'Ghost Town',
      'Nightclub',
      'Colosseum',
      'County',
      'Police Station',
      'Embassy',
      'Convent',
      'Cruise Ship',
      'Sea Cave',
      'Depot',
      'Embassy',
      'Factory',
      'Lighthouse',
      'Slum',
      'Ocean Trench',
      'Gas Station',
      'Glacier',
      'Great Wall',
      'Farm',
      'Hideout',
      'Church',
      'Rainforest',
      'Lake',
      'Lagoon',
      'Plain',
      'Dungeon',
      'Black Market',
      'Monastery',
      'Mount Everest',
      'Mountain',
      'Morgue',
      'Medieval Wall',
      'Spaceship',
      'Snowfield',
      'Oasis',
      'Observatory',
      'Olympus',
      'Palace',
      'Swamp',
      'Oil Rig',
      'Prairie',
      'Maximum Security Prison',
      'Ghost Village',
      'Harbor',
      'Shelter',
      'River',
      'Skyscraper',
      'Ruins',
      'Savanna',
      'Emergency Room',
      'Game Room',
      'Sanctuary',
      'Submarine',
      'Mayan Temple',
      'Eiffel Tower',
      'Bermuda Triangle',
      'Valley',
      'Landfill',
      'Combat Zone',
      'Radioactive Zone',
      'Arctic',
      'Bamboo Forest',
      'Bayou',
      'Canyon',
      'Catacomb',
      'Checkpoint',
      'Cliffside',
      'Command Center',
      'Crater',
      'Crystal Cave',
      'Dead Sea',
      'Death Row',
      'Dimension Gate',
      'Docking Bay',
      'Frozen Tundra',
      'Gorge',
      'Grand Canyon',
      'Haunted House',
      'Hidden Fortress',
      'Iceberg',
      'Interrogation Room',
      'Landfill',
      'Marshland',
      'Mirage City',
      'Outpost',
      'Plateau',
      'Reef',
      'Sewer',
      'Shipwreck',
      'Space Station',
      'Swampland',
      'Throne Room',
      'Underground City',
      'Waterfall',
      'Airbase',
      'Alcatraz',
      'Alleyway',
      'Amphitheater',
      'Arcade',
      'Armory',
      'Asylum',
      'Atoll',
      'Backcountry',
      'Barrack',
      'Barricade',
      'Basilica',
      'Bathhouse',
      'Biome',
      'Bluff',
      'Boathouse',
      'Boneyard',
      'Botanical Garden',
      'Burial Site',
      'Cabin',
      'Caldera',
      'Camp',
      'Canteen',
      'Cape',
      'Capital City',
      'Cargo Bay',
      'Cathedra',
      'Citadel',
      'Civic Center',
      'Cliffhanger',
      'Coal Mine',
      'Colony',
      'Combat Post',
      'Commune',
      'Compound',
      'Convention Center',
      'Coral Reef',
      'Corral',
      'Courtroom',
      'Crevasse',
      'Cul-de-sac',
      'Dead End',
      'Deck',
      'Detention Center',
      'Dive Bar',
      'Dock',
      'Drainage Canal',
      'Drive-In',
      'Drug Den',
      'Estuary',
      'Excavation Site',
      'Facility',
      'Fjord',
      'Floodplain',
      'Foothold',
      'Foxhole',
      'Frontier',
      'Geyser',
      'Ghost Ship',
      'Gorge',
      'Graveyard',
      'Grid',
      'Hangar',
      'Hot Spring',
      'Impound Lot',
      'Inlet',
      'Jailhouse',
      'Junk Yard',
      'Jungle Outpost',
      'Keep',
      'Landing Zone',
      'Laneway',
      'Lava Field',
      'Loading Dock',
      'Lookout Tower',
      'Maze',
      'Meadow',
      'Medical Bay',
      'Mesa',
      'Military Base',
      'Moat',
      'Moor',
      'Mossy Cave',
      'Nuclear Silo',
      'Observatory Deck',
      'Pier',
      'Power Plant',
      'Rally Point',
      'Research Station',
      'Ridge',
      'Rooftop Garden',
      'Safe House',
      'Salt Flat',
      'Sandbar',
      'Scrapyard',
      'Seaside',
      'Secret Vault',
      'Settlement',
      'Shrubland',
      'Solitary Confinement',
      'Summit',
      'Tank',
      'Terminal',
      'Tidal Pool',
      'Tollbooth',
      'Trading Post',
      'Vault',
      'Watchtower',
      'Wetland',
    ],
  ),
  const Category(
    id: 'animales',
    name: 'Animals',
    icon: '🦁',
    color: Colors.green,
    words: [
      'Bee',
      'Eagle',
      'Axolotl',
      'Moose',
      'Spider',
      'Squirrel',
      'Armadillo',
      'Ostrich',
      'Whale',
      'Owl',
      'Donkey',
      'Horse',
      'Goat',
      'Camel',
      'Crab',
      'Kangaroo',
      'Capybara',
      'Beaver',
      'Zebra',
      'Pig',
      'Monkey',
      'Cheetah',
      'Swan',
      'Crocodile',
      'Hummingbird',
      'Rabbit',
      'Coyote',
      'Dolphin',
      'Elephant',
      'Scorpion',
      'Flamingo',
      'Seal',
      'Hen',
      'Cat',
      'Gorilla',
      'Cricket',
      'Worm',
      'Hamster',
      'Hippopotamus',
      'Ant',
      'Ferret',
      'Iguana',
      'Jaguar',
      'Giraffe',
      'Koala',
      'Lion',
      'Wolf',
      'Parrot',
      'Butterfly',
      'Bat',
      'Bear',
      'Pigeon',
      'Duck',
      'Turkey',
      'Dog',
      'Penguin',
      'Octopus',
      'Frog',
      'Mouse',
      'Rhinoceros',
      'Snake',
      'Shark',
      'Tiger',
      'Turtle',
      'Cow',
      'Fox',
      'Albatross',
      'Bull Moose',
      'Alpaca',
      'Anaconda',
      'Eel',
      'Antelope',
      'Slug',
      'Catfish',
      'Barracuda',
      'Bison',
      'Boa',
      'Vulture',
      'Buffalo',
      'Seahorse',
      'Snail',
      'Caribou',
      'Mountain Beaver',
      'Caiman',
      'Chameleon',
      'Carp',
      'Cassowary',
      'Aardvark',
      'Deer',
      'Stork',
      'Cobra',
      'Dwarf Hummingbird',
      'Condor',
      'Cormorant',
      'Raven',
      'Grass Snake',
      'Cuscus',
      'Hyrax',
      'Dugong',
      'Emu',
      'Hedgehog',
      'Beetle',
      'Starfish',
      'Pheasant',
      'Gazelle',
      'Tortoise',
      'Goose',
      'Gharial',
      'Seagull',
      'Gibbon',
      'Wolverine',
      'Macaw',
      'Guanaco',
      'Cheetah',
      'Guppy',
      'Hyena',
      'Ibis',
      'Jacamar',
      'Boar',
      'Kiwi',
      'Lizard',
      'Lamprey',
      'Lobster',
      'Barn Owl',
      'Lemur',
      'Leopard',
      'Hare',
      'Lynx',
      'Llama',
      'Sea Lion',
      'Glow Worm',
      'Manatee',
      'Mandrill',
      'Mongoose',
      'Raccoon',
      'Marmot',
      'Jellyfish',
      'Mussel',
      'Spider Monkey',
      'Walrus',
      'Shrew',
      'Narwhal',
      'Otter',
      'Okapi',
      'Orangutan',
      'Orca',
      'Oyster',
      'Panda',
      'Panther',
      'Macaw',
      'Peacock',
      'Pelican',
      'Sloth',
      'Swordfish',
      'Clownfish',
      'Python',
      'Moth',
      'Quetzal',
      'Naked Mole Rat',
      'Stingray',
      'Reindeer',
      'Salamander',
      'Salmon',
      'Cuttlefish',
      'Rattlesnake',
      'Tapir',
      'Badger',
      'Termite',
      'Mole',
      'Toucan',
      'Deer',
      'Viper',
      'Mink',
      'Wombat',
      'Yak',
      'Opossum',
      'Alligator',
      'Clam',
      'Amoeba',
      'Ermine',
      'Donkey',
      'Bluefin Tuna',
      'Wasp',
      'Albino Axolotl',
      'Sea Slug',
      'River Catfish',
      'Blue Whale',
      'Barbel',
      'Stick Insect',
      'American Bison',
      'Black Vulture',
      'Seahorse',
      'Cockatoo',
      'Canary',
      'Tiny Crab',
      'Caracal',
      'Rattle',
      'European Beaver',
      'Porcupine',
      'Jackal',
      'Chimpanzee',
      'Red Deer',
      'Civet',
      'Coati',
      'King Cobra',
      'Andean Condor',
      'Roe Deer',
      'Parakeet',
      'Dingo',
      'Komodo Dragon',
      'Dromedary',
      'Dugong',
      'Echidna',
      'Dung Beetle',
      'Golden Pheasant',
      'Leopard Seal',
      'Thomson Gazelle',
      'Greyhound',
      'Wildcat',
      'Sparrowhawk',
      'Gecko',
      'Gyrfalcon',
      'Arctic Wolverine',
      'Swallow',
      'Crane',
      'Patagonian Guanaco',
      'Peregrine Falcon',
      'Hippocampus',
      'African Boar',
      'Monitor Lizard',
      'Lemming',
      'Snow Leopard',
      'Iberian Lynx',
      'Ethiopian Wolf',
      'Firefly',
      'Manta Ray',
      'Monarch Butterfly',
      'Meerkat',
      'Capuchin Monkey',
      'Proboscis Monkey',
      'Tsetse Fly',
      'Rhea',
      'Platypus',
      'Giant Anteater',
      'Red Panda',
      'Polar Bear',
      'Giant Panda',
      'Mandarin Duck',
      'Mallard',
      'Three-toed Sloth',
      'Pufferfish',
      'Flying Fish',
      'Emperor Penguin',
      'Foal',
      'Spiny Porcupine',
      'Quokka',
      'Kangaroo Rat',
      'White Rhinoceros',
      'King Snake',
      'Amazon Tapir',
      'Tasmanian Devil',
      'Bengal Tiger',
      'Wallaby',
      'Wildebeest',
    ],
  ),
];

// ==========================================
// BASE DE DATOS: PORTUGUÉS (~2100 palavras)
// ==========================================
final List<Category> _categoriesPt = [
  const Category(
    id: 'mix',
    name: 'Aleatório',
    icon: '🎲',
    color: Colors.purple,
    words: [
      'Buraco Negro',
      'Alquimista',
      'Amnésia',
      'Apocalipse',
      'Astronauta',
      'Átomo',
      'Avatar',
      'Bateria',
      'Bitcoin',
      'Bunker',
      'Cavaleiro',
      'Camaleão',
      'Catapulta',
      'Cinderela',
      'Centauro',
      'Ciborgue',
      'Dinossauro',
      'Dragão',
      'Esfinge',
      'Extraterrestre',
      'Fantasma',
      'Frankenstein',
      'Gênio',
      'Gravidade',
      'Feitiço',
      'Fada',
      'Hipnose',
      'Ilusão',
      'Karma',
      'Labirinto',
      'Magia',
      'Múmia',
      'Mutante',
      'Ninja',
      'Óvni',
      'Pirata',
      'Portal',
      'Robô',
      'Sereia',
      'Super-herói',
      'Telepatia',
      'Vampiro',
      'Viking',
      'Zumbi',
      'Alquimia',
      'Amuleto',
      'Arco-íris',
      'Arqueiro',
      'Caixão',
      'Atlântico',
      'Aurora Boreal',
      'Pé Grande',
      'Bruxa',
      'Bruxaria',
      'Crânio',
      'Capa Invisível',
      'Cápsula do Tempo',
      'Cataclismo',
      'Clone',
      'Código Secreto',
      'Cometa',
      'Constelação',
      'Criptonita',
      'Cristal Mágico',
      'Caverna',
      'Ciber',
      'Déjà Vu',
      'Destino',
      'Dimensão',
      'Deusa',
      'Eclipse',
      'Elfo',
      'Anão',
      'Encruzilhada',
      'Energia',
      'Enigma',
      'Espejismo',
      'Espião',
      'Espírito',
      'Estrela',
      'Explosão',
      'Faraó',
      'Prazo',
      'Fênix',
      'Fóssil',
      'Gárgula',
      'Gladiador',
      'Golem',
      'Grifo',
      'Guerreiro',
      'Holograma',
      'Lobisomem',
      'Ícaro',
      'Imperador',
      'Ladrão',
      'Lenda',
      'Lanterna',
      'Chave Mestra',
      'Mestre',
      'Borboleta de Fogo',
      'Matrix',
      'Medusa',
      'Mente Coletiva',
      'Mentiroso',
      'Meteorito',
      'Minotauro',
      'Mistério',
      'Mito',
      'Morgana',
      'Monge',
      'Nirvana',
      'Oráculo',
      'Orc',
      'Escuridão',
      'Pégaso',
      'Poltergeist',
      'Poseidon',
      'Profecia',
      'Prometeu',
      'Quimera',
      'Ressurreição',
      'Rex',
      'Ritual',
      'Runas',
      'Samurai',
      'Satélite',
      'Sombra',
      'Feitiçaria',
      'Subconsciente',
      'Talismã',
      'Templo',
      'Tempo',
      'Titã',
      'Totem',
      'Troll',
      'Tsunami',
      'Unicórnio',
      'Universo Paralelo',
      'Valquíria',
      'Feiticeiro',
      'Buraco de Minhoca',
      'Yeti',
      'Zeus',
      'Apocalipse Zumbi',
      'Zona Morta',
      'Abismo',
      'Adivinha',
      'Anjo Caído',
      'Anomalia',
      'Antimatéria',
      'Arma Secreta',
      'Astral',
      'Aura',
      'Besta',
      'Biomecânico',
      'Caos',
      'Sentinela',
      'Chakra',
      'Código Binário',
      'Convergência',
      'Coroa Mágica',
      'Cripta',
      'Cristal de Poder',
      'Cruzada',
      'Curandeira',
      'Cyberpunk',
      'Daemon',
      'Desaparecimento',
      'Desintegração',
      'Deus Esquecido',
      'Distopia',
      'Divino',
      'Domínio',
      'Doppelganger',
      'Encantamento',
      'Espadachim',
      'Espectro',
      'Eterno',
      'Éter',
      'Exorcismo',
      'Fatalidade',
      'Força Sombria',
      'Galáxia',
      'Fenda Dimensional',
      'Guardião',
      'Irmandade',
      'Heroína',
      'Homem de Areia',
      'Horizonte',
      'Ícone',
      'Mundo Inferior',
      'Interdimensional',
      'Invisibilidade',
      'Magia Proibida',
      'Liche',
      'Mente Mestra',
      'Metamorfose',
      'Mundo Espelho',
      'Néctar',
      'Necrópolis',
      'Nexo',
      'Necromante',
      'Ninfas',
      'Noite Eterna',
      'Núcleo',
      'Obsidiana',
      'Ogro',
      'Onisciente',
      'Ônix',
      'Pacto Sombrio',
      'Paradoxo',
      'Planeta Vermelho',
      'Poeira Estelar',
      'Primitivo',
      'Fugitivo',
      'Reencarnação',
      'Relicário',
      'Selo',
      'Sinal',
      'Simulacro',
      'Singularidade',
      'Subterrâneo',
      'Supernovas',
      'Telepático',
      'Testamento',
      'Armadilha',
      'Transgressão',
      'Viagem Astral',
      'Visão',
      'Vórtice',
      'Safira Maldita',
      'Âncora Cósmica',
      'Armadura de Sombra',
      'Névoa Eterna',
      'Cachoeira de Fogo',
      'Cicatriz do Tempo',
      'Código de Honra',
      'Quartzo Negro',
      'Clarão',
      'Essência Pura',
      'Espada Rúnica',
      'Metamorfo',
      'Fragmento',
      'Grimório',
      'Serafim',
      'Espectro',
      'Vazio',
      'Espírito Errante',
      'Anjo Guardião',
      'Magia Proibida',
    ],
  ),
  const Category(
    id: 'fiesta',
    name: 'Festa',
    icon: '🍻',
    color: Colors.pink,
    words: [
      'Bafômetro',
      'Alto-falante',
      'Ano Novo',
      'Balada',
      'Bartender',
      'Casamento',
      'Bêbado',
      'Petiscos',
      'Cerveja',
      'Champanhe',
      'Show',
      'Ressaca',
      'DJ',
      'Fantasia',
      'Karaokê',
      'Dose',
      'Pinhata',
      'Bolo',
      'Balões',
      'Convite',
      'Dança',
      'Ressaca',
      'Tequila',
      'Vodka',
      'Rum',
      'Vinho',
      'Gelo',
      'Copo',
      'Brinde',
      'Despedida de Solteiro',
      'Confete',
      'VIP',
      'Pulseira',
      'Segurança',
      'After Party',
      'Animador',
      'Bar Aberto',
      'Barril',
      'Garrafada',
      'Garrafa',
      'Bufê',
      'Cabine',
      'Boteco',
      'Carnaval',
      'Cassino',
      'Celebração',
      'Cerveja Artesanal',
      'Coquetel',
      'Foguete',
      'Taça',
      'Brinde',
      'Dado',
      'Aniversário',
      'Discoteca',
      'Fantasiado',
      'Drink',
      'Euforia',
      'Festa Temática',
      'Flores',
      'Fogueira',
      'Fogos de Artifício',
      'Gim',
      'Boné',
      'Torneira de Cerveja',
      'Banda',
      'Happy Hour',
      'Horchata',
      'Jarra',
      'Jogo de Bebida',
      'Lima',
      'Limão',
      'Louco',
      'Luzes Coloridas',
      'Forró',
      'Máscara',
      'Mesas',
      'Mezcal',
      'Caipirinha',
      'Mirrorball',
      'Mocktail',
      'Mojito',
      'Música ao Vivo',
      'Véspera de Natal',
      'Open Bar',
      'Bar Crawl',
      'Caneca',
      'Pirotecnia',
      'Piscina',
      'Pôquer',
      'Festa na Piscina',
      'Posada',
      'Verdade ou Desafio',
      'Pub',
      'Debutante',
      'Rodadas',
      'Roleta',
      'Sangria',
      'Selfie',
      'Serpentina',
      'Sidra',
      'Som',
      'Surpresa',
      'Jogo de Tabuleiro',
      'Palco',
      'Terraço',
      'Cobertura',
      'Tonel',
      'Bebidas',
      'Dose Dupla',
      'Dose Tripla',
      'Gole',
      'Despedida de Solteira',
      'Gelatina Alcoólica',
      'Copo Virado',
      'Pong de Cerveja',
      'Saúde',
      'Conga',
      'Flashmob',
      'Bastão de Luz',
      'Cabine de Fotos',
      'Playlist',
      'RSVP',
      'Toga Party',
      'Noite de Quiz',
      'Pós-festa',
      'Animador',
      'Despedida de Solteira',
      'Bandana',
      'Conta do Bar',
      'Bartending',
      'Festa',
      'Estouro',
      'Pintura Corporal',
      'Pula-pula',
      'Catering',
      'Celebração',
      'Mímica',
      'Virar de Uma Vez',
      'Noite de Clube',
      'Cerveja Gelada',
      'Contagem Regressiva',
      'Drinque Artesanal',
      'Pista de Dança',
      'Sinuca',
      'Festa durante o Dia',
      'Bola de Espelho',
      'Brinde Surpresa',
      'Dress Code',
      'Escorregão',
      'Bis',
      'Cerimonialista',
      'Pintura Facial',
      'Documento Falso',
      'Roupa Extravagante',
      'Festa de Espuma',
      'Fondue',
      'Entrada Gratuita',
      'Function',
      'Noite de Jogos',
      'Reunião',
      'Lista de Convidados',
      'Barraquinha',
      'Festa Caseira',
      'Quebra-gelo',
      'Instagramável',
      'Jukebox',
      'Microfone de Karaokê',
      'Festa do Barril',
      'Limousine',
      'Banda ao Vivo',
      'Trancado',
      'Long Island',
      'Margarita',
      'Meia-noite',
      'Misturador',
      'Cachaça',
      'Teatro de Mistério',
      'Luz Neon',
      'Última Rodada',
      'Vida Noturna',
      'Chapéu Engraçado',
      'Microfone Aberto',
      'Ônibus de Festa',
      'Lembrança',
      'Buzina de Festa',
      'Organização de Festa',
      'Punchline',
      'Rave',
      'Reunião',
      'Caça ao Tesouro',
      'Coqueteleira',
      'Beba e Pinte',
      'Festa do Pijama',
      'Água com Gás',
      'Bebida Espirituosa',
      'Spritzer',
      'Despedida do Noivo',
      'Ponto de Encontro',
      'Festa de Rua',
      'Tailgate',
      'Chá da Tarde',
      'Bar Tiki',
      'Alegre',
      'Suéter Feio',
      'Vibe',
      'Uísque',
      'Peruca',
      'Quintal',
      'Zero Álcool',
      'Jogos de Arcada',
      'Chá de Bebê',
      'Dicas de Bartender',
      'Cortinas Blackout',
      'Festa de Bairro',
      'Brunch Party',
      'Karaokê no Carro',
      'Bolo de Celebração',
      'Tinir de Copos',
      'Hora do Coquetel',
      'Cold Brew',
      'Noite de Comédia',
      'Concurso de Fantasias',
      'Taxa de Entrada',
      'Batalha de Dança',
      'Motorista Designado',
      'Jantar de Festa',
      'Canudo',
      'Float',
      'Zona de Diversão',
      'Apresentador de Jogos',
      'Troca de Presentes',
      'Grande Abertura',
      'Convidado Especial',
      'Festa de Chapéu',
      'Festa de Fim de Ano',
      'Quebra-gelo em Grupo',
      'DJ Residente',
      'Suco Bar',
      'Cordão de Identificação',
      'Luau',
      'Carnaval',
      'Sociabilizar',
      'Bar de Mocktail',
      'Festival de Música',
      'Coruja da Noite',
      'Intruso na Festa',
      'Photo Op',
      'Macarrão de Piscina',
      'Quiz do Bar',
      'Copo Vermelho',
      'Festa em Estrada',
      'Faixa de Festa',
      'Amigo Secreto',
      'Pijama Party',
      'Hora Social',
      'Suco com Gás',
      'Garrafa Giratória',
      'Bebidas Temáticas',
      'Tiara de Festa',
    ],
  ),
  const Category(
    id: 'cine',
    name: 'Cinema',
    icon: '🎬',
    color: Colors.blue,
    words: [
      'Ação',
      'Ator',
      'Tapete Vermelho',
      'Alien',
      'Anime',
      'Câmera',
      'Cinema Mudo',
      'Comédia',
      'Diretor',
      'Documentário',
      'Efeitos Especiais',
      'Roteiro',
      'Hollywood',
      'Oscar',
      'Pipoca',
      'Terror',
      'Bilheteria',
      'Trailer',
      'Vilão',
      'Protagonista',
      'Dublê',
      'Maquiagem',
      'Figurino',
      'Tela Verde',
      'Sequência',
      'Trilogia',
      'Claquete',
      'Curta-metragem',
      'Animação',
      'Musical',
      'Aclamado',
      'Atuação',
      'Adaptação',
      'Agente',
      'Aluguel',
      'Animatrônico',
      'Antagonista',
      'Público',
      'Autobiografia',
      'Cinebiografia',
      'Blockbuster',
      'Fracasso de Bilheteria',
      'Cameo',
      'Casting',
      'CGI',
      'Ficção Científica',
      'Cinematografia',
      'Cinéfilo',
      'Clássico',
      'Clube de Fãs',
      'Código Hays',
      'Colorização',
      'Comédia Romântica',
      'Competição',
      'Continuidade',
      'Créditos',
      'Crítica',
      'Dublagem',
      'Drama',
      'Edição',
      'Elenco',
      'Estreia',
      'Fantasia',
      'Festival',
      'Flashback',
      'Formato IMAX',
      'Fotograma',
      'Franquia',
      'Gangster',
      'Gênero',
      'Gore',
      'Roteirista',
      'História',
      'Independente',
      'Longa-metragem',
      'Lente',
      'Melodrama',
      'Metragem',
      'Montagem',
      'Multiverso',
      'Narração',
      'Nomeação',
      'Tela',
      'Sessão de Imprensa',
      'Filme de Culto',
      'Percepção',
      'Reviravolta',
      'Pós-produção',
      'Prêmio',
      'Produção',
      'Produtora',
      'Projetor',
      'Remake',
      'Elenco',
      'Avaliação',
      'Filmagem',
      'Sala de Cinema',
      'Trilha Sonora',
      'Spin-off',
      'Spoiler',
      'Suspense',
      'Tecnologia',
      'Telão',
      'Thriller',
      'Streaming',
      'Unboxing',
      'Faroeste',
      'Widescreen',
      'Zoom',
      'Anti-herói',
      'Arco',
      'Auteur',
      'Backstory',
      'Box Set',
      'Audição',
      'Personagem',
      'Diretor de Fotografia',
      'Cliffhanger',
      'Close-up',
      'Gradação de Cor',
      'Alívio Cômico',
      'Conflito',
      'Grua',
      'Corte Rápido',
      'Comédia Sombria',
      'Cena de Morte',
      'Desfecho',
      'Diálogo',
      'Som Diegético',
      'Film Noir',
      'Freeze Frame',
      'Fusão de Gêneros',
      'Iluminação',
      'Reconhecimento de Locação',
      'MacGuffin',
      'Metáfora',
      'Mockumentary',
      'Monólogo',
      'Dilema Moral',
      'Plano Geral',
      'Edição Paralela',
      'Plot Armor',
      'Efeito Prático',
      'Adereço',
      'Pista Falsa',
      'Ação Crescente',
      'Transição de Cena',
      'Cenografia',
      'Showrunner',
      'Câmera Lenta',
      'Sósia',
      'Material de Arquivo',
      'Simbolismo',
      'Time-lapse',
      'Plano Americano',
      'Narração em Off',
      'Bloqueio',
      'Chamada de Retorno',
      'Catarse',
      'Perseguição',
      'Clímax',
      'Abertura Fria',
      'Paleta de Cores',
      'Coreografia de Luta',
      'Montagem Paralela',
      'Cena de Massa',
      'Cena Diurna',
      'Engano',
      'Dissolução',
      'Ângulo Holandês',
      'Elipse',
      'Elenco Conjunto',
      'Plano de Estabelecimento',
      'Exposição',
      'Prenúncio',
      'Quarta Parede',
      'Ghost Writer',
      'Hora Dourada',
      'Plano do Herói',
      'Ângulo Alto',
      'Homenagem',
      'Reviravolta de Identidade',
      'Intercalação',
      'Íris',
      'Justaposição',
      'Tiro Fatal',
      'Ângulo Baixo',
      'Corte Combinado',
      'Cena de Memória',
      'Cena Pós-Créditos Intermediária',
      'Cena do Espelho',
      'Desvio de Atenção',
      'Visão Noturna',
      'Sequência de Abertura',
      'História de Origem',
      'Plano Aéreo',
      'Panorâmica',
      'Perspectiva',
      'Ponto de Virada',
      'Ponto de Vista',
      'Cena Pós-Créditos',
      'Plano de Poder',
      'Plano de Perfil',
      'Prólogo',
      'Reinicialização',
      'Arco de Redenção',
      'Revelação',
      'Contra-plano',
      'Rebobinar',
      'Roubo de Cena',
      'Plano do Horizonte',
      'Prévia',
      'Storyboard',
      'Subtrama',
      'Final Surpresa',
      'Contagem Regressiva',
      'Cartão de Título',
      'Final com Reviravolta',
      'Bloqueio de Cena',
      'Ato de Abertura',
      'Personagem Secundário',
      'Roteiro Original',
      'Cenas Deletadas',
      'Diretor de Casting',
      'Épico',
      'Estética Visual',
      'Fiasco de Bilheteria',
      'Grabação ao Vivo',
      'Imersivo',
      'Licença Artística',
      'Olhar da Câmera',
      'Palcos',
      'Abertura do Ato',
      'Personagem Secundário',
      'Roteiro Original',
      'Cenas Deletadas',
      'Diretor de Casting',
      'Épico Histórico',
      'Estética Cinematográfica',
      'Fracasso de Bilheteria',
      'Herói Improvável',
      'Identidade Oculta',
      'Jornada do Herói',
      'Liga de Fãs',
      'Momento de Revelação',
      'Narrador Não-Confiável',
      'Oscilação de Humor',
      'Paródia',
      'Personagem de Apoio',
      'Universo Cinematográfico',
    ],
  ),
  const Category(
    id: 'comida',
    name: 'Comida',
    icon: '🌮',
    color: Colors.orange,
    words: [
      'Abacate',
      'Asinhas',
      'Arroz',
      'Bacon',
      'Burrito',
      'Café',
      'Cereal',
      'Chocolate',
      'Hambúrguer',
      'Sorvete',
      'Cachorro-quente',
      'Pizza',
      'Sushi',
      'Tacos',
      'Pamonha',
      'Espaguete',
      'Queijo',
      'Salada',
      'Sopa',
      'Pão',
      'Manteiga',
      'Biscoito',
      'Bolo',
      'Donut',
      'Waffle',
      'Crepe',
      'Sanduíche',
      'Ketchup',
      'Mostarda',
      'Maionese',
      'Batata Frita',
      'Abobrinha',
      'Água de Coco',
      'Defumado',
      'Alho',
      'Almôndega',
      'Amêndoa',
      'Anchova',
      'Atum',
      'Churrasco',
      'Berbigão',
      'Birria',
      'Bolinho',
      'Pãozinho',
      'Burritos',
      'Amendoim',
      'Caldo',
      'Camarão',
      'Carne Assada',
      'Panela',
      'Ceviche',
      'Chalupa',
      'Chocolate Quente',
      'Torresmo',
      'Pimenta',
      'Açaí',
      'Linguiça',
      'Churros',
      'Leitão',
      'Côco',
      'Codorna',
      'Consomê',
      'Costela',
      'Creme',
      'Croquete',
      'Nugget',
      'Vagem',
      'Milho',
      'Empanada',
      'Enchilada',
      'Caldo de Feijão',
      'Frango',
      'Flan',
      'Fondue',
      'Morango',
      'Feijão',
      'Frutas',
      'Gazpacho',
      'Gelatina',
      'Gordita',
      'Molho',
      'Guacamole',
      'Peixe Grelhado',
      'Farinha',
      'Ovos',
      'Hummus',
      'Presunto',
      'Suco de Frutas',
      'Tomate',
      'Lasanha',
      'Leite',
      'Alface',
      'Lentilhas',
      'Limonada',
      'Lombo',
      'Milho Verde',
      'Manga',
      'Frutos do Mar',
      'Paçoca',
      'Mocotó',
      'Milanesa',
      'Moqueca',
      'Laranja',
      'Raspadinha',
      'Quiabo',
      'Nuggets',
      'Pinheiro',
      'Paella',
      'Picolé',
      'Palmito',
      'Mamão',
      'Macarrão',
      'Empada',
      'Pepino',
      'Carne de Porco',
      'Pozole',
      'Polvo',
      'Quesadilla',
      'Queijo Derretido',
      'Carne de Vaca',
      'Recheio',
      'Risoto',
      'Salsicha',
      'Molho de Tomate',
      'Melancia',
      'Bauru',
      'Siri',
      'Tapioca',
      'Torta',
      'Tasajo',
      'Tapioca Frita',
      'Brigadeiro',
      'Coxinha',
      'Pastel',
      'Pão de Queijo',
      'Frango Assado',
      'Churrascaria',
      'Feijoada',
      'Picanha',
      'Caipirinha',
      'Mousse',
      'Pavê',
      'Pudim',
      'Acarajé',
      'Água de Coco',
      'Defumado',
      'Alho',
      'Almôndega',
      'Amêndoa',
      'Anchova',
      'Atum',
      'Churrasco',
      'Berbigão',
      'Birria',
      'Bolinho de Bacalhau',
      'Pãozinho',
      'Salgado',
      'Amendoim',
      'Caldo Verde',
      'Camarão',
      'Carne de Sol',
      'Panela de Barro',
      'Ceviche',
      'Chalupa',
      'Chocolate Quente',
      'Torresmo',
      'Pimenta',
      'Açaí na Tigela',
      'Linguiça',
      'Churros',
      'Leitão',
      'Côco',
      'Codorna',
      'Consomê',
      'Cupim',
      'Creme de Leite',
      'Croquete',
      'Nugget',
      'Vagem',
      'Pamonha',
      'Empanada',
      'Enchilada',
      'Caldo de Feijão',
      'Frango',
      'Flan',
      'Fondue',
      'Morango',
      'Feijão Tropeiro',
      'Frutas Tropicais',
      'Gazpacho',
      'Gelatina',
      'Gordita',
      'Molho Pesto',
      'Guacamole',
      'Peixe Grelhado',
      'Farinha de Mandioca',
      'Ovos',
      'Hummus',
      'Presunto',
      'Suco Verde',
      'Tomate Cereja',
      'Lasanha',
      'Leite',
      'Alface',
      'Lentilhas',
      'Limonada',
      'Lombo',
      'Paçoca',
      'Manga',
      'Frutos do Mar',
      'Rapadura',
      'Mocotó',
      'Milanesa',
      'Moqueca',
      'Laranja',
      'Raspadinha',
      'Quiabo',
      'Carne Assada',
      'Paella',
      'Picolé de Coco',
      'Palmito',
      'Mamão',
      'Macarrão',
      'Empada',
      'Pepino',
      'Carne de Porco',
      'Fígado',
      'Polvo',
      'Quesadilla',
      'Queijo Coalho',
      'Carne de Vaca',
      'Recheado',
      'Risoto',
      'Salsicha',
      'Molho de Tomate',
      'Melancia',
      'Baião de Dois',
      'Siri Mole',
      'Tapioca',
      'Torta Capixaba',
      'Carne Seca',
      'Pé de Moleque',
      'Curau',
      'Paçoca',
      'Canjica',
      'Mungunzá',
      'Arroz Doce',
      'Doce de Leite',
      'Ambrosia',
      'Quindim',
      'Cocada',
      'Beijinho',
      'Bem-casado',
    ],
  ),
  const Category(
    id: 'lugares',
    name: 'Lugares',
    icon: '🌍',
    color: Colors.teal,
    words: [
      'Aeroporto',
      'Banco',
      'Biblioteca',
      'Floresta',
      'Bar',
      'Prisão',
      'Castelo',
      'Cemitério',
      'Cinema',
      'Circo',
      'Deserto',
      'Escola',
      'Espaço',
      'Estádio',
      'Farmácia',
      'Academia',
      'Hospital',
      'Hotel',
      'Ilha',
      'Laboratório',
      'Lua',
      'Marte',
      'Mina',
      'Museu',
      'Oceano',
      'Parque',
      'Praia',
      'Restaurante',
      'Selva',
      'Supermercado',
      'Teatro',
      'Torre de Controle',
      'Túnel',
      'Universidade',
      'Veterinária',
      'Vulcão',
      'Zoológico',
      'Aquário',
      'Aldeia',
      'Armazém',
      'Antártida',
      'Sótão',
      'Autoestrada',
      'Spa',
      'Bairro',
      'Adega',
      'Bunker Secreto',
      'Bordel',
      'Beco',
      'Campo de Guerra',
      'Campo Minado',
      'Canal do Panamá',
      'Caverna',
      'Usina Nuclear',
      'Shopping',
      'Cidade Fantasma',
      'Clube Noturno',
      'Coliseu',
      'Comarca',
      'Delegacia',
      'Embaixada',
      'Convento',
      'Navio de Cruzeiro',
      'Gruta Marinha',
      'Depósito',
      'Fábrica',
      'Farol',
      'Favela',
      'Fossa Oceânica',
      'Posto de Gasolina',
      'Geleira',
      'Grande Muralha',
      'Fazenda',
      'Esconderijo',
      'Igreja',
      'Floresta Tropical',
      'Lago',
      'Lagoa',
      'Planície',
      'Masmorra',
      'Mercado Negro',
      'Mosteiro',
      'Monte Everest',
      'Montanha',
      'Necrotério',
      'Muralha Medieval',
      'Nave Espacial',
      'Campos Nevados',
      'Oásis',
      'Observatório',
      'Olimpo',
      'Palácio',
      'Pântano',
      'Plataforma de Petróleo',
      'Pradaria',
      'Presídio de Alta Segurança',
      'Vila Abandonada',
      'Porto',
      'Abrigo',
      'Rio',
      'Arranha-céu',
      'Ruínas',
      'Savana',
      'Pronto-Socorro',
      'Sala de Jogos',
      'Santuário',
      'Submarino',
      'Templo Maia',
      'Torre Eiffel',
      'Triângulo das Bermudas',
      'Vale',
      'Aterro Sanitário',
      'Zona de Combate',
      'Zona Radioativa',
      'Ártico',
      'Bambuzal',
      'Bayou',
      'Cânion',
      'Catacumba',
      'Posto de Controle',
      'Penhasco',
      'Centro de Comando',
      'Cratera',
      'Caverna de Cristal',
      'Mar Morto',
      'Corredor da Morte',
      'Portal Dimensional',
      'Doca',
      'Tundra Congelada',
      'Garganta',
      'Grand Canyon',
      'Casa Mal-assombrada',
      'Fortaleza Escondida',
      'Iceberg',
      'Sala de Interrogatório',
      'Pântano',
      'Cidade Miragem',
      'Posto Avançado',
      'Planalto',
      'Recife',
      'Esgoto',
      'Naufrágio',
      'Estação Espacial',
      'Pantanal',
      'Sala do Trono',
      'Cidade Subterrânea',
      'Cachoeira',
      'Base Aérea',
      'Alcatraz',
      'Beco',
      'Anfiteatro',
      'Fliperama',
      'Armaria',
      'Manicômio',
      'Atol',
      'Interior',
      'Barraca',
      'Barricada',
      'Basílica',
      'Banho Público',
      'Bioma',
      'Falésia',
      'Boathouse',
      'Cemitério de Aviões',
      'Jardim Botânico',
      'Sítio Arqueológico',
      'Cabana',
      'Caldera',
      'Acampamento',
      'Cantina',
      'Cabo',
      'Capital',
      'Porão de Carga',
      'Catedral',
      'Cidadela',
      'Centro Cívico',
      'Mina de Carvão',
      'Colônia',
      'Posto de Combate',
      'Comunidade',
      'Complexo Militar',
      'Centro de Convenções',
      'Recife de Coral',
      'Curral',
      'Tribunal',
      'Crevassa',
      'Beco Sem Saída',
      'Corredor da Morte',
      'Deck',
      'Centro de Detenção',
      'Bar Barato',
      'Doca',
      'Canal de Drenagem',
      'Drive-In',
      'Antro',
      'Estuário',
      'Sítio de Escavação',
      'Instalação',
      'Fiorde',
      'Várzea',
      'Posição',
      'Trincheira',
      'Fronteira',
      'Gêiser',
      'Navio Fantasma',
      'Desfiladeiro',
      'Cemitério',
      'Grade',
      'Hangar',
      'Fonte Termal',
      'Pátio de Apreensão',
      'Enseada',
      'Cadeia',
      'Ferro-velho',
      'Posto Avançado da Selva',
      'Fortaleza',
      'Zona de Pouso',
      'Viela',
      'Campo de Lava',
      'Plataforma de Carga',
      'Torre de Observação',
      'Labirinto',
      'Prado',
      'Enfermaria',
      'Mesa',
      'Base Militar',
      'Fosso',
      'Charneca',
      'Caverna com Musgo',
      'Silo Nuclear',
      'Deck do Observatório',
      'Píer',
      'Usina',
      'Ponto de Reunião',
      'Estação de Pesquisa',
      'Cume',
      'Tanque',
      'Terminal',
      'Piscina de Maré',
      'Pedágio',
      'Entreposto',
      'Cofre',
      'Torre de Vigilância',
      'Brejo',
      'Favelão',
      'Aeródromo',
      'Beco Sem Saída',
      'Campo de Treino',
      'Quadra Esportiva',
      'Capelinha',
    ],
  ),
  const Category(
    id: 'animales',
    name: 'Animais',
    icon: '🦁',
    color: Colors.green,
    words: [
      'Abelha',
      'Águia',
      'Axolote',
      'Alce',
      'Aranha',
      'Esquilo',
      'Tatu',
      'Avestruz',
      'Baleia',
      'Coruja',
      'Burro',
      'Cavalo',
      'Cabra',
      'Camelo',
      'Caranguejo',
      'Canguru',
      'Capivara',
      'Castor',
      'Zebra',
      'Porco',
      'Macaco',
      'Guepardo',
      'Cisne',
      'Crocodilo',
      'Beija-flor',
      'Coelho',
      'Coiote',
      'Golfinho',
      'Elefante',
      'Escorpião',
      'Flamingo',
      'Foca',
      'Galinha',
      'Gato',
      'Gorila',
      'Grilo',
      'Verme',
      'Hamster',
      'Hipopótamo',
      'Formiga',
      'Furão',
      'Iguana',
      'Jaguar',
      'Girafa',
      'Coala',
      'Leão',
      'Lobo',
      'Papagaio',
      'Borboleta',
      'Morcego',
      'Urso',
      'Pombo',
      'Pato',
      'Peru',
      'Cachorro',
      'Pinguim',
      'Polvo',
      'Sapo',
      'Rato',
      'Rinoceronte',
      'Cobra',
      'Tubarão',
      'Tigre',
      'Tartaruga',
      'Vaca',
      'Raposa',
      'Albatroz',
      'Alce Macho',
      'Alpaca',
      'Anaconda',
      'Enguia',
      'Antílope',
      'Lesma',
      'Bagre',
      'Barracuda',
      'Bisão',
      'Jiboia',
      'Abutre',
      'Búfalo',
      'Cavalo-marinho',
      'Caracol',
      'Caribu',
      'Castor da Montanha',
      'Caimão',
      'Camaleão',
      'Carpa',
      'Casuar',
      'Tamanduá',
      'Cervo',
      'Cegonha',
      'Naja',
      'Beija-flor Anão',
      'Condor',
      'Cormorão',
      'Corvo',
      'Cobra-cipó',
      'Cuscos',
      'Hírax',
      'Dugongo',
      'Emu',
      'Ouriço',
      'Besouro',
      'Estrela do Mar',
      'Faisão',
      'Gazela',
      'Galápago',
      'Ganso',
      'Gavial',
      'Gaivota',
      'Gibão',
      'Glutão',
      'Arara',
      'Guanaco',
      'Chita',
      'Gupy',
      'Hiena',
      'Íbis',
      'Jacamar',
      'Javali',
      'Kiwi',
      'Lagartixa',
      'Lampreia',
      'Lagosta',
      'Coruja Celeiro',
      'Lêmure',
      'Leopardo',
      'Lebre',
      'Lince',
      'Lhama',
      'Leão-marinho',
      'Minhoca Luminosa',
      'Peixe-boi',
      'Mandril',
      'Mangusto',
      'Guaxinim',
      'Marmota',
      'Água-viva',
      'Mexilhão',
      'Macaco-aranha',
      'Morsa',
      'Musaranho',
      'Narval',
      'Lontra',
      'Okapi',
      'Orangotango',
      'Orca',
      'Ostra',
      'Panda',
      'Pantera',
      'Arara-azul',
      'Pavão',
      'Pelicano',
      'Preguiça',
      'Peixe-espada',
      'Peixe-palhaço',
      'Píton',
      'Mariposa',
      'Quetzal',
      'Toupeira-nua',
      'Arraia',
      'Rena',
      'Salamandra',
      'Salmão',
      'Choco',
      'Cascavel',
      'Anta',
      'Texugo',
      'Cupim',
      'Toupeira',
      'Tucano',
      'Veado',
      'Víbora',
      'Vison',
      'Wombat',
      'Iaque',
      'Gambá',
      'Aligátor',
      'Amêijoa',
      'Ameba',
      'Arminho',
      'Jumento',
      'Atum Rojo',
      'Vespa',
      'Axolote Albino',
      'Lesma do Mar',
      'Bagre do Rio',
      'Baleia Azul',
      'Barbo',
      'Inseto-Pau',
      'Bisão Americano',
      'Abutre Negro',
      'Cavalinho do Mar',
      'Cacatua',
      'Canário',
      'Carangueijinho',
      'Caracal',
      'Castor Europeu',
      'Porco-espinho',
      'Chacal',
      'Chimpanzé',
      'Veado Vermelho',
      'Civeta',
      'Quati',
      'Naja Real',
      'Condor dos Andes',
      'Corça',
      'Periquito',
      'Dingo',
      'Dragão de Komodo',
      'Dromedário',
      'Dugongo',
      'Equidna',
      'Besouro Rola-bosta',
      'Faisão Dourado',
      'Foca Leopardo',
      'Gazela de Thomson',
      'Galgo',
      'Gato-bravo',
      'Gavião',
      'Geco',
      'Gerfalcão',
      'Glutão Ártico',
      'Andorinha',
      'Grou',
      'Guanaco Patagônico',
      'Falcão-peregrino',
      'Hipocampo',
      'Javali Africano',
      'Lagarto Monitor',
      'Lemingue',
      'Leopardo das Neves',
      'Lince Ibérico',
      'Lobo Etíope',
      'Vagalume',
      'Manta Raia',
      'Borboleta Monarca',
      'Suricato',
      'Macaco-prego',
      'Macaco Narigudo',
      'Mosca Tsé-tsé',
      'Ema',
      'Ornitorrinco',
      'Tamanduá-bandeira',
      'Panda Vermelho',
      'Urso Polar',
      'Panda Gigante',
      'Pato Mandarim',
      'Pato Selvagem',
      'Bicho-preguiça',
      'Baiacu',
      'Peixe-voador',
      'Pinguim Imperador',
      'Potro',
      'Ouriço-cacheiro',
      'Quokka',
      'Rato-canguru',
      'Rinoceronte Branco',
      'Cobra-rei',
      'Anta Amazônica',
      'Diabo da Tasmânia',
      'Tigre de Bengala',
      'Ualabi',
      'Gnu',
    ],
  ),
];
