const Map<String, String> de = {
  'txt_version': 'v2.1.0 Open Source',
  'config_title': 'Einstellungen',
  'config_impostors': 'Impostor',
  'config_time': 'Zeit',
  'config_edit_punishments': 'Strafen bearbeiten',
  'config_btn_start': 'STARTEN',
  'create_min_words': 'Mindestens 5 Wörter',
  'create_title_edit': 'Bearbeiten',
  'create_title_new': 'Erstellen',
  'create_input_name': 'Name',
  'create_input_emoji': 'Emoji',
  'create_words_title': 'Wörter',
  'create_input_word': 'Wort...',
  'create_btn_save': 'SPEICHERN',
  'login_turn_of': 'Spielzug von',
  'players_title': 'Spieler',
  'players_btn_continue': 'WEITER',
  'players_input_name': 'Name',
  'players_input_pin': 'PIN',
  'punishments_title': 'Strafen anpassen',
  'punishments_input_hint': 'Neue Strafe (z.B. Runde ausgeben)',
  'punishments_swipe_delete': 'Zum Löschen wischen',
  'punishments_restore_title': 'Zurücksetzen?',
  'punishments_restore_desc': 'Deine eigenen Strafen werden gelöscht.',
  'punishments_btn_cancel': 'ABBRECHEN',
  'punishments_btn_restore': 'ZURÜCKSETZEN',
  'result_win_civilians': 'ZIVILISTEN GEWINNEN!',
  'result_win_impostor': 'IMPOSTOR GEWINNT!',
  'result_punish_impostor': 'Strafe für den IMPOSTOR',
  'result_punish_civilians': 'Strafe für die ZIVILISTEN',
  'result_btn_exit': 'VERLASSEN',
  'result_btn_play_again': 'NOCHMAL SPIELEN',
  'result_btn_spin': 'DREHEN',
  'result_luck': 'VIEL GLÜCK!',
  'result_your_punishment': '🔥 DEINE STRAFE 🔥',
  'result_btn_accept': 'AKZEPTIEREN',
  'reveal_hold': 'GEDRÜCKT HALTEN',
  'reveal_to_see': 'um deine geheime Karte zu sehen',
  'reveal_impostor': 'IMPOSTOR',
  'reveal_civilian': 'ZIVILIST',
  'reveal_deceive': 'Täusche alle!',
  'reveal_top_secret': 'STRENG GEHEIM',
  'reveal_btn_continue': 'WEITER',
  'timer_time_up': 'ZEIT ABGELAUFEN!',
  'timer_btn_vote': 'ABSTIMMEN',
  'timer_debate': 'DISKUSSION',
  'voting_title': 'Wer lügt?',
  'voting_confirm_title': 'Für [NAME] stimmen?',
  'voting_btn_cancel': 'ABBRECHEN',
  'voting_btn_confirm': 'BESTÄTIGEN',
};

const List<String> defaultPunishmentsDe = [
  "🍺 Ex dein Getränk!",
  "💃 Tanze 30 Sekunden lang verrückt",
  "🏋️ Mache sofort 10 Kniebeugen",
  "📱 Lass die anderen deine letzte WhatsApp lesen",
  "🐔 Mach ein Huhn nach, das ein Ei legt",
  "🧊 Kaue auf einem Eiswürfel, bis er schmilzt",
  "🎤 Singe den Refrain deines Lieblingsliedes",
  "😳 Beichte dein seltsamstes Guilty Pleasure",
  "📸 Poste ein Selfie mit einer fiesen Grimasse",
  "🤫 Bleibe die ganze nächste Runde stumm",
  "🤸 Mache 5 Liegestütze",
  "🫂 Umarme den Spieler zu deiner Rechten",
];
