const Map<String, String> fr = {
  'txt_version': 'v2.1.0 Open Source',
  'config_title': 'Paramètres',
  'config_impostors': 'Imposteurs',
  'config_time': 'Temps',
  'config_edit_punishments': 'Modifier les Gages',
  'config_btn_start': 'COMMENCER',
  'create_min_words': 'Minimum 5 mots',
  'create_title_edit': 'Modifier',
  'create_title_new': 'Créer',
  'create_input_name': 'Nom',
  'create_input_emoji': 'Émoji',
  'create_words_title': 'Mots',
  'create_input_word': 'Mot...',
  'create_btn_save': 'ENREGISTRER',
  'login_turn_of': 'Au tour de',
  'players_title': 'Joueurs',
  'players_btn_continue': 'CONTINUER',
  'players_input_name': 'Nom',
  'players_input_pin': 'PIN',
  'punishments_title': 'Éditer Gages',
  'punishments_input_hint': 'Nouveau gage (ex: Payer un verre)',
  'punishments_swipe_delete': 'Balayer pour supprimer',
  'punishments_restore_title': 'Restaurer ?',
  'punishments_restore_desc': 'Tes gages personnalisés seront supprimés.',
  'punishments_btn_cancel': 'ANNULER',
  'punishments_btn_restore': 'RESTAURER',
  'result_win_civilians': 'LES CIVILS GAGNENT !',
  'result_win_impostor': 'L\'IMPOSTEUR GAGNE !',
  'result_punish_impostor': 'Gage pour l\'IMPOSTEUR',
  'result_punish_civilians': 'Gage pour les CIVILS',
  'result_btn_exit': 'QUITTER',
  'result_btn_play_again': 'REJOUER',
  'result_btn_spin': 'TOURNER LA ROUE',
  'result_luck': 'BONNE CHANCE !',
  'result_your_punishment': '🔥 TON GAGE 🔥',
  'result_btn_accept': 'ACCEPTER',
  'reveal_hold': 'MAINTENIR APPUYÉ',
  'reveal_to_see': 'pour voir ta carte secrète',
  'reveal_impostor': 'IMPOSTEUR',
  'reveal_civilian': 'CIVIL',
  'reveal_deceive': 'Trompe tout le monde !',
  'reveal_top_secret': 'TOP SECRET',
  'reveal_btn_continue': 'CONTINUER',
  'timer_time_up': 'TEMPS ÉCOULÉ !',
  'timer_btn_vote': 'VOTER',
  'timer_debate': 'DÉBAT',
  'voting_title': 'Qui ment ?',
  'voting_confirm_title': 'Voter contre [NAME] ?',
  'voting_btn_cancel': 'ANNULER',
  'voting_btn_confirm': 'CONFIRMER',
};

const List<String> defaultPunishmentsFr = [
  "🍺 Cul sec !",
  "💃 Danse n'importe comment pendant 30 secondes",
  "🏋️ Fais 10 squats tout de suite",
  "📱 Laisse-les lire ton dernier message WhatsApp",
  "🐔 Imite une poule qui pond un œuf",
  "🧊 Mâche un glaçon jusqu'à ce qu'il fonde",
  "🎤 Chante le refrain de ta chanson préférée",
  "😳 Avoue ton plaisir coupable le plus bizarre",
  "📸 Poste un selfie avec une grimace atroce",
  "🤫 Reste silencieux tout le prochain tour",
  "🤸 Fais 5 pompes",
  "🫂 Fais un gros câlin au joueur à ta droite",
];
