const Map<String, String> ja = {
  'txt_version': 'v2.1.0 Open Source',
  'config_title': '設定',
  'config_impostors': 'インポスター',
  'config_time': '制限時間',
  'config_edit_punishments': '罰ゲームを編集',
  'config_btn_start': 'ゲーム開始！',
  'create_min_words': '最低5つの単語が必要です',
  'create_title_edit': '編集',
  'create_title_new': '作成',
  'create_input_name': '名前',
  'create_input_emoji': '絵文字',
  'create_words_title': '単語',
  'create_input_word': '単語を入力...',
  'create_btn_save': '保存',
  'login_turn_of': 'のターン',
  'players_title': 'プレイヤー',
  'players_btn_continue': '次へ',
  'players_input_name': '名前',
  'players_input_pin': 'PINコード',
  'punishments_title': '罰ゲームの編集',
  'punishments_input_hint': '新しい罰ゲーム (例: 飲み代をおごる)',
  'punishments_swipe_delete': 'スワイプで削除',
  'punishments_restore_title': 'リセットする？',
  'punishments_restore_desc': 'カスタム罰ゲームはすべて消去されます。',
  'punishments_btn_cancel': 'キャンセル',
  'punishments_btn_restore': 'リセット',
  'result_win_civilians': '市民の勝利！',
  'result_win_impostor': 'インポスターの勝利！',
  'result_punish_impostor': 'インポスターへの罰',
  'result_punish_civilians': '市民への罰',
  'result_btn_exit': '終了',
  'result_btn_play_again': 'もう一度プレイ',
  'result_btn_spin': 'ルーレットを回す',
  'result_luck': 'グッドラック！',
  'result_your_punishment': '🔥 あなたの罰ゲーム 🔥',
  'result_btn_accept': '受け入れる',
  'reveal_hold': '長押し',
  'reveal_to_see': 'してシークレットカードを見る',
  'reveal_impostor': 'インポスター',
  'reveal_civilian': '市民',
  'reveal_deceive': 'みんなを騙し切れ！',
  'reveal_top_secret': 'トップシークレット',
  'reveal_btn_continue': '次へ',
  'timer_time_up': '時間切れ！',
  'timer_btn_vote': '投票する',
  'timer_debate': '議論タイム',
  'voting_title': '嘘つきは誰だ？',
  'voting_confirm_title': '[NAME] に投票する？',
  'voting_btn_cancel': 'キャンセル',
  'voting_btn_confirm': '確定',
};

const List<String> defaultPunishmentsJa = [
  "🍺 飲み物を一気飲み！",
  "💃 30秒間全力で踊る！",
  "🏋️ 今すぐスクワット10回",
  "📱 最新のLINEを読み上げられる",
  "🐔 卵を産むニワトリのモノマネ",
  "🧊 氷が溶けるまで噛み砕く",
  "🎤 好きな曲のサビを熱唱する",
  "😳 誰にも言えない秘密の趣味を告白する",
  "📸 変顔の自撮りをSNSにアップ",
  "🤫 次のラウンドは一言も喋っちゃダメ",
  "🤸 腕立て伏せを5回やる",
  "🫂 右隣のプレイヤーをハグする",
];
