const Map<String, String> zh = {
  'txt_version': 'v2.1.0 Open Source',
  'config_title': '游戏设置',
  'config_impostors': '内鬼人数',
  'config_time': '时间',
  'config_edit_punishments': '编辑惩罚',
  'config_btn_start': '开始游戏',
  'create_min_words': '最少5个词',
  'create_title_edit': '编辑',
  'create_title_new': '创建',
  'create_input_name': '名称',
  'create_input_emoji': '表情',
  'create_words_title': '词语',
  'create_input_word': '输入词语...',
  'create_btn_save': '保存',
  'login_turn_of': '当前轮到',
  'players_title': '玩家',
  'players_btn_continue': '继续',
  'players_input_name': '名字',
  'players_input_pin': '密码',
  'punishments_title': '编辑惩罚',
  'punishments_input_hint': '新惩罚 (例如: 请客吃饭)',
  'punishments_swipe_delete': '滑动以删除',
  'punishments_restore_title': '恢复默认?',
  'punishments_restore_desc': '您的自定义惩罚将被删除。',
  'punishments_btn_cancel': '取消',
  'punishments_btn_restore': '恢复',
  'result_win_civilians': '平民获胜！',
  'result_win_impostor': '内鬼获胜！',
  'result_punish_impostor': '给内鬼的惩罚',
  'result_punish_civilians': '给平民的惩罚',
  'result_btn_exit': '退出',
  'result_btn_play_again': '再来一局',
  'result_btn_spin': '转动轮盘',
  'result_luck': '祝你好运！',
  'result_your_punishment': '🔥 你的惩罚 🔥',
  'result_btn_accept': '接受',
  'reveal_hold': '长按屏幕',
  'reveal_to_see': '查看你的身份牌',
  'reveal_impostor': '内鬼',
  'reveal_civilian': '平民',
  'reveal_deceive': '骗过所有人！',
  'reveal_top_secret': '绝密',
  'reveal_btn_continue': '继续',
  'timer_time_up': '时间到！',
  'timer_btn_vote': '投票',
  'timer_debate': '讨论时间',
  'voting_title': '谁在撒谎？',
  'voting_confirm_title': '投票给 [NAME]？',
  'voting_btn_cancel': '取消',
  'voting_btn_confirm': '确定',
};

const List<String> defaultPunishmentsZh = [
  "🍺 感情深，一口闷！（干了你的饮料）",
  "💃 随便跳段舞，持续30秒",
  "🏋️ 立刻做10个深蹲",
  "📱 让人大声读出你最后一条微信",
  "🐔 模仿母鸡下蛋",
  "🧊 嘴里含一块冰块直到融化",
  "🎤 唱你最喜欢的一首歌的高潮部分",
  "😳 坦白你最奇怪的“恶趣味”",
  "📸 拍一张鬼脸自拍并发朋友圈",
  "🤫 下一轮全程不许说话",
  "🤸 做5个俯卧撑",
  "🫂 拥抱你右边的玩家",
];
